 
<?php 	
if($this->ermsg !='')
{
?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				No data found.
	</div>
<?php 
}
else
{	
	sapp_Global::generateClientValidations($this->form);?>
<div id="error_message" style="display:none;"></div>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="panel-title">EEOC Category</div>
    </div>
<form class="form-horizontal" name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction();?>" method="<?php echo $this->form->getMethod(); ?>">
		<?php echo $this->form->id; ?>
    
        <div class="panel-body"> 
                    <div class="row">                                       
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="col-md-3 control-label required">EEOC Category <img class="tooltip" title="Ex: Craft Workers, Operatives, Sales Workers" src="<?php echo MEDIA_PATH;?>images/help.png"></label>
			<div class="col-md-9"><?php echo $this->form->eeoccategory; ?></div>
			<?php if(isset($this->msgarray['eeoccategory'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->eeoccategory->getId(); ?>"><?php echo $this->msgarray['eeoccategory'];?></span>
			<?php }?>
			</div>
			
			<div class="form-group">
                        <label class="col-md-3 control-label">Description</label>
			<div class="col-md-9"><?php echo $this->form->description; ?></div>
			</div>

		</div></div></div>
		<div class="panel-footer">
		<?php echo $this->form->submit; ?>
                    <button onclick="window.location.href='<?php echo BASE_URL; ?>eeoccategory';" type="button" class="btn btn-danger" >Cancel</button>
		</div>
 
</form>
</div>

<?php	}	?>