<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

 <?php if (count($this->messages)) {?>
	<div id="test">
    <?php 
			foreach ($this->messages as $message)
			{
				$flag = array();				
				$flag = array_keys($message);
				echo "<div id='messageData' class='ml-alert-1-$flag[0]' style='margin-bottom: 0px;'><div style='display:block;'><span class='style-1-icon $flag[0]'></span>";
				echo $message[$flag[0]];
				echo "</div></div>";
			} 
	?>	
   </div> 
	
<?php } ?>

<?php 
if($this->ermsg !='')
{
?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				No data found.
	</div>
<?php 
}
else
{
sapp_Global::generateClientValidations($this->form);
if($this->emptyFlag != 0)
	{
?>
<?php	}	?>
<div id="error_message" style="display:none;"></div>

<form name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction();?>" method="<?php echo $this->form->getMethod(); ?>">
<div class="form_cntr_block_70">

		<?php echo $this->form->id; 
			echo $this->form->emptyFlag; 
		?>
                <input type="hidden" id="defaultId" value="<?php echo $this->id;?>">
		<input type="hidden" name="currencyid" id="currencyid" value="<?php echo $this->currencyid;?>"/>
        <div class="total-form-controller">
		
		   <div class="new-form-ui clearb">
			  <label class="required">Employee </label>
			<div class="division"><?php echo $this->form->to_id; ?>
			<?php if(isset($this->msgarray['to_id'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->to_id->getId(); ?>"><?php echo $this->msgarray['to_id'];?></span>
			<?php }?>
			</div>
		</div>
			
			
			 
			 
			 	
		<div class="new-form-ui clearb sm_currency">
        
			    <label class="required"><?php echo $this->form->currency_id->getLabel(); ?></label>
                
				<div class="division">
				<?php echo $this->form->currency_id; ?>
				<?php echo $this->form->amount; ?>
				<?php if(isset($this->msgarray['currency_id'])){?>
				   <div class="errors" style="position: relative; top: inherit;" id="errors-<?php echo $this->form->currency_id->getId(); ?>">
				   	<?php echo $this->msgarray['currency_id'];?>
                   </div>
				<?php }?>
                
				
				
				   <input type="hidden" name="cal_amount" id="cal_amount" value="">
				 <div id="currencynamediv" style="display:none; float:left; width: 100%;">
                      <span id="currencyname"></span>   
                          <span class="cxcText">
                             
                                <span class="cxcEdit" style="display:inline-block;"><?php echo !empty($this->cal_amount)?$this->cal_amount:((!empty($this->data['advance_conversion_rate']))?$this->data['advance_conversion_rate']:0);?></span>
								
                               
                                  <input class="cxcInput" min="1" style="display:none;" type="number" step="any"/> <?php echo $this->currency;?>
                           </span>
                     </div>          
				<?php if(isset($this->msgarray['amount'])){?>
				   <div class="errors" style="position: relative; top: inherit;" id="errors-<?php echo $this->form->amount->getId(); ?>">
				   	<?php echo $this->msgarray['amount'];?>
                   </div>
				<?php }?>
				
				</div>
				
			</div>
			
			 <div class="new-form-ui">
			  <label >EMI</label>
			<div class="division"><?php echo $this->form->emi_months; ?></div>
			<?php if(isset($this->msgarray['emi_months'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->emi_months->getId(); ?>"><?php echo $this->msgarray['emi_months'];?></span>
			<?php }else {?>
					   <span class="errors" id="errors-<?php echo $this->form->emi_months->getId(); ?>" style="display:none;"></span>
				  <?php }?>
			</div>

		
				<div class="new-form-ui clearb">
			    <label class="required" >Payment Mode</label>
				<div class="division"><?php echo $this->form->payment_mode_id; ?>
				<?php if(isset($this->msgarray['payment_mode_id'])){?>
				   <span class="errors" style="width: 100%;" id="errors-<?php echo $this->form->payment_mode_id->getId(); ?>"><?php echo $this->msgarray['payment_mode_id'];?></span>
				<?php }?>
				</div>
			</div>
			
	
			
			 <div class="new-form-ui">
			  <label>Payment Ref # </label>
			<div class="division"><?php echo $this->form->payment_ref_number; ?>
			<?php if(isset($this->msgarray['payment_ref_number'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->payment_ref_number->getId(); ?>"><?php echo $this->msgarray['payment_ref_number'];?></span>
			<?php }?>
			</div>
			</div>
			
			<div class="new-form-ui clearb textareaheight">
			  <label>Description</label>
			<div class="division"><?php echo $this->form->description; ?></div>
			</div>
			
		<div class="new-form-ui-submit">
		<?php echo $this->form->submit; ?>
		<button onclick="window.location.href='<?php echo BASE_URL; ?>payrollemployeeadvances/';" type="button" id="Cancel" name="Cancel">Cancel</button>
		</div>
            <div class="form_full_block cb">
                <div class="emiGrid">
                </div>
                   
		</div></div>
</form>
		</div>

	
<?php } ?>	

<!--<script type="text/javascript" language="javascript" src="<?php //echo EXPENSES_MEDIA_PATH?>js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php //echo EXPENSES_MEDIA_PATH?>js/jquery-ui.js"></script>
 <script type="text/javascript" language="javascript" src="<?php //echo EXPENSES_MEDIA_PATH?>js/materialize.js"></script>
 <script type="text/javascript" language="javascript" src="<?php //echo EXPENSES_MEDIA_PATH?>js/scripts.js"></script>-->
<script type="text/javascript" language="javascript" src="<?php echo EXPENSES_MEDIA_PATH?>js/scripts.js"></script>
<script type="text/javascript" language="javascript">
$(document).ready(function(){


	   var currencyid=$("#currency_id").val();
		var application_currencyid=$("#currencyid").val();


		var currency='1'+$("#currency_id option:selected").text()+'=';
		$("#currencyname").html(currency);

		
		if(currencyid=='' || currencyid==application_currencyid)
		{
			$("#currencynamediv").hide();
		}
		else if(application_currencyid!='')
		{
			
			$("#currencynamediv").show();
		}
		
//             var defaultId =  $("#defaultId").val();   
//             if(defaultId !='')
//             {
//                 CalculateEMI($("#amount").val() , $("#emi_months").val());
//             }
	
	
	});
	
	$(function() {
	  $('#sm_currency').addClass('sm_currency');
          
          $('#amount').change(function(){
              CalculateEMI($("#amount").val() , $("#emi_months").val());
          });
          
          $("#emi_months").change(function(){
              CalculateEMI($("#amount").val() , $("#emi_months").val());
          })
	});
        
        function getCurrencyAdvances()
        {

            var currency_id=$("#currency_id").val();
            var application_currencyid=$("#currencyid").val();
                if(currency_id=='' || currency_id==application_currencyid)
                {
                        $("#currencynamediv").hide();
                }
                else if(application_currencyid!='')
                {

                        $("#currencynamediv").show();
                }

                var currency='1'+$("#currency_id option:selected").text()+'=';
                $("#currencyname").html(currency);
        }
        
        function CalculateEMI($amount , $months)
        {
            var monthNames = ["January", "February", "March", "April", "May", "June","July", "August", "September", "October", "November", "December"];
            $maiDiv = "<div id='grid_emiGrid' class='all-grid-control'>";
            $maiDiv += "<div class='slimScrollDiv' style='position: relative; overflow: hidden; width: 250px; height: auto;'>";
            $maiDiv += "<div id='emiGrid1' class='details_data_display_block newtablegrid' style='overflow: hidden; width: 250px; height: auto; background: rgb(204, 204, 204) none repeat scroll 0% 0%; padding-bottom: 10px;'>";
            $tableHtml = "";
            if($amount != null && $amount > 0 && $months != null && $months > 0)
            {
               var currentDate = new Date();
               var emiDate = currentDate;
               var actualMonth = $("#emi_months option:selected").text()
               var perMonth = Math.ceil($amount /actualMonth) ;
               
               $tableHtml += "<table class='grid' width='100%' cellspacing='0' cellpadding='4' border='0' align='center'><thead><tr>";
               $tableHtml += "<th><b>Name</b></th>";
               $tableHtml += "<th><b>Month</b></th>";
               $tableHtml += "<th><b>Amount</b></th>";
               //$tableHtml += "<th><b>Status</b></th>";
               $tableHtml += "</tr></thead><tbody>";
               for (var i = 0; i < actualMonth; i++) {
                   emiDate.setMonth(currentDate.getMonth() + (1));
                   $tableHtml += "<tr class='row1'><td>EMI"+(i+1)+"</td>";
                   $tableHtml += "<td>"+ monthNames[emiDate.getMonth()] +" - "+emiDate.getFullYear()+"</td>";
                   $tableHtml += "<td>"+perMonth+"</td>";
                   //$tableHtml += "<td> Not Paid </td>";
                   $tableHtml += "</tr>";
               }
               $tableHtml += "</tbody></table>";
               
            }
            $maiDiv +=$tableHtml;
            $maiDiv +="</div></div></div>"
            if($tableHtml == "")
            {
            }
            else
            {
            $(".emiGrid").html($maiDiv);
            }
        }
</script>
<style type="text/css">
    .sCurrency {
        width: 60px !important;
        float: left;
    }
    .sCurrency > .select2-choice {
        width: 60px !important;
    }
    .sAmount {
    width: 105px !important;
    margin-left: 18px;
    }
    .emiGrid {
    float: left;
    width: 750px !important;
    }
</style>
		



