	<?php if($this->ermsg !='')
{
?><div class="full_container cwrap">
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				No data found.
	</div>
    </div>
<?php 
}
else
{
$baseUrl = $this->serverUrl().$this->baseUrl();
$data = $this->data;
$loginuser =$this->loginUserId;
 ?>

   
    <div class="clearfix"></div>
    <div class="full_container cwrap" style="position: relative;">
           <div>
                <div class="col-main">
                    <div class="expview_status">
                        <div class="expvs_col vrdln">
                            
                        </div>
                    </div>
                </div>
                <div class="col-right">
                  
                </div>
            </div>
			<div class="action_btns" style="width: inherit; float:right;">
            	
            </div>
            <div class="">
                
                <div class="expview_details cds5">
                    
                    <?php if(count($this->data)>0) {
							foreach($this->data as $adv){	
						
						
							?>
                    <?php if($adv["Pay_status"]!='0'){
                        
                    
                   
                      sapp_Helper::viewHeader();
                                sapp_Helper::viewBody('alt','Name',(!empty($adv['to_name']))?$adv['to_name']:"...",'Date',(!empty($adv['createddate']))?sapp_Global::change_date($adv['createddate'],'view'):"...");
                                sapp_Helper::viewBody('alt','EMI Months',(!empty($adv['emi_months']))?$adv['emi_months']:"...",'Ammount',(!empty($adv['amount']))?$adv['currencycode'].'-'.$adv['amount']:"...");
                                sapp_Helper::viewBody('alt','Pay Status',(!empty($adv['Pay_status']))?"Paid":"...",'Paid Date',(!empty($adv['Paid_date']))?sapp_Global::change_date($adv['Paid_date'],'view'):"...");
                                sapp_Helper::viewBody('alt','EMI Amount',(!empty($adv['emiammount']))?$adv['emiammount']:"...");
                                sapp_Helper::viewFooter();
                    } else {
                         sapp_Helper::viewHeader();
                                sapp_Helper::viewBody('alt','Name',(!empty($adv['to_name']))?$adv['to_name']:"...",'Date',(!empty($adv['createddate']))?sapp_Global::change_date($adv['createddate'],'view'):"...");
                                sapp_Helper::viewBody('alt','EMI Months',(!empty($adv['emi_months']))?$adv['emi_months']:"...",'Ammount',(!empty($adv['amount']))?$adv['currencycode'].'-'.$adv['amount']:"...");
                                 sapp_Helper::viewBody('alt','Pay Status',(empty($adv['Pay_status']))?"Not Paid":"...",'Paid Date',(!empty($adv['Paid_date']))?sapp_Global::change_date($adv['Paid_date'],'view'):"...");
                                 sapp_Helper::viewBody('alt','EMI Amount',(!empty($adv['emiammount']))?$adv['emiammount']:"...");
                                sapp_Helper::viewFooter();
                    }?>
                    
                    <?php } ?>
						<?php } ?>
                    <div class="new-form-ui-submit">
                    <input type="button" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
                    <button onclick="window.location.href='<?php echo BASE_URL; ?>payrollemployeeadvances';" type="button" id="Cancel" name="Cancel">Cancel</button>
                    </div>
                </div>
            </div>
			
	 
			<?php	}	?> 
    </div>




<script type="text/javascript" language="javascript">
$('#amountreturn').hover(function(ev){
    $('.returnadvance').stop(true,true).fadeIn(); 
},function(ev){
    $('.returnadvance').stop(true,true).fadeOut();
}).mousemove(function(ev){
    $('.returnadvance').css({left:ev.layerX+10,top:ev.layerY+10});
});


</script>
<style>
	.all-grid-control .addrecord {margin-right: 0;}
</style>