<?php
/* * ******************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 * ****************************************************************************** */
if($this->ermsg !='')
		{
?>
     <div class="ml-alert-1-info m1-info-set"><div class="style-1-icon info"></div>No data found.</div>
<?php }else
	{
		 if($this->popup == 'close') { ?> 	
			<div class="ml-alert-1-success">
			<div class="style-1-icon success"></div>
			Category <?php echo $this->eventact; ?> successfully
			</div>
		
		<?php 	 }else{ 	
		 sapp_Global::generateClientValidations($this->form);
		 $request = Zend_Controller_Front::getInstance();
		 $actionName = $request->getRequest()->getActionName();
		 	if($actionName == 'view')
		 	  $viewclass = 'view-form-detail';
		 	else
		 	  $viewclass = '';  
		 ?>
			<div id="error_message" style="display:none;"></div>
                        <div class="form_cntr_block">
			<form name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction();?>" method="<?php echo $this->form->getMethod(); ?>">
					
					<?php $this->form->getAction();?>
			        <div class="total-form-controller <?php echo $viewclass;?>">
                            <?php  if($this->flag!='view'){ ?>
                            <?php echo sapp_Helper::sd_form_helper($this->msgarray, $this->form, 'from_date', '','','required',array());?>
                            <?php echo sapp_Helper::sd_form_helper($this->msgarray, $this->form, 'to_date', '','','required',array());?>
                            <?php echo sapp_Helper::sd_form_helper($this->msgarray, $this->form, 'shift_id', '','','required',array());?>
                            <?php echo sapp_Helper::sd_form_helper($this->msgarray, $this->form, 'emp_id', '','','required',array());?>

							<?php }else{
								sapp_Helper::viewHeader();
                                sapp_Helper::viewBody('alt','Shift Name',(!empty($this->data['shift_name']))?$this->data['shift_name']:"...",'Short Name',(!empty($this->data['shortname']))?$this->data['shortname']:"...");
                                sapp_Helper::viewBody('alt','On Duty Time',(!empty($this->data['onduty_time']))?$this->data['onduty_time']:"...",'Begin Intime',(!empty($this->data['begin_intime']))?$this->data['begin_intime']:"...");
                                sapp_Helper::viewBody('alt','Off Duty Time',(!empty($this->data['offduty_time']))?$this->data['offduty_time']:"...",'Late (min\'s)',(!empty($this->data['late_min']))?$this->data['late_min']:"...");
                                sapp_Helper::viewFooter();
								}
							 ?>	
					<div class="new-form-ui-submit">
					<?php echo $this->form->submit; ?>
					<?php if($actionName == 'addpopup') { ?>
					    <button onclick="closeiframepopup('<?php echo $this->controllername;?>','cancel');"  type="button" >Cancel</button>
					<?php }else{?>
						<?php if($actionName == 'view'){?>
							<input type="button" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
						<?php }?>
						<button onclick="window.location.href='<?php echo BASE_URL; ?>shifttypes';" type="button" id="Cancel" name="Cancel">Cancel</button>
					<?php }?>	
					</div>
				</div>
				
			</form>
</div>
<?php }?>
<!--<script language='javascript' type='text/javascript'>

	<?php if($this->popup != '') { ?>
	  closeiframeAddPopup("<?php echo $this->departmentData ;?>",'<?php echo $this->controllername; ?>','service_desk_id','category'); 					
	<?php } ?>
</script>-->
                        <script src='<?php echo MEDIA_PATH;?>timepicker/jquery.timepicker.js' type='text/javascript' ></script>
                       <script src='<?php echo MEDIA_PATH;?>timepicker/jquery.timepicker.min.js' type='text/javascript' ></script>
                       <script src='<?php echo MEDIA_PATH;?>timepicker/jquery.timepicker.css' type='text/javascript' ></script>
        <script src="<?php echo MEDIA_PATH;?>js/jscolor.min.js"></script>
        <script type='text/javascript'>
$(document).ready(function(){
  
var yearrange = <?php echo "'".date("Y", strtotime("-1 years")).':'.(date('Y')+1)."'"; ?>;
 
//var yearrange = <?php //echo "'".date('Y').':'.date('Y')."'"; ?>;

//$('#from_date').datepicker({
//
//				showOn:'both',
//				yearRange: yearrange,
//				dateFormat: '<?php //echo DATEFORMAT_JS;?>//',
//				buttonImage: "<?php //echo $this->baseUrl("public/media/images/cal.jpg");?>//",
//				buttonImageOnly: true,
//				buttonText: "",
//				changeMonth: true,
//				changeYear: true,
//                                showButtonPanel: true ,
//                                maxDate: 'today',
//				onClose:function(){
//                                    $('#holidaydate').trigger('blur');
//                                }
//
//		});
//$('#to_date').datepicker({
//
//				showOn:'both',
//				yearRange: yearrange,
//				dateFormat: '<?php //echo DATEFORMAT_JS;?>//',
//				buttonImage: "<?php //echo $this->baseUrl("public/media/images/cal.jpg");?>//",
//				buttonImageOnly: true,
//				buttonText: "",
//				changeMonth: true,
//				changeYear: true,
//                                showButtonPanel: true ,
//                                maxDate: 'today',
//				onClose:function(){
//                                    $('#to_date').trigger('blur');
//                                }
//
//		});
                $('#onduty_time').timepicker();
                $('#offduty_time').timepicker();
                $('#late_min').timepicker();
                $('#leaveearly_min').timepicker();
                $('#begin_intime').timepicker();
                $('#end_intime').timepicker();
                $('#begin_outtime').timepicker();
                $('#end_outtime').timepicker();
                
});
function setTextColor(picker) {
    document.getElementsByTagName('body')[0].style.color = '#' + picker.toString()
}
</script>

<?php }?>