 <div class="form_cntr_block">

<?php 
if($this->ermsg !='')
{
?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				No data found.
	</div>
<?php
}else
{ 
$baseUrl = $this->serverUrl().$this->baseUrl();
echo $this->form->id; ?>
<?php 
sapp_Helper::viewHeader();
sapp_Helper::viewBody('nor','Geography Code',$this->data['geographycode'],'Default Geography Group',(!empty($this->data['defaultGeographyGroup']))?$this->data['defaultGeographyGroup']:"...");
sapp_Helper::viewBody('alt','Geography Group',(!empty($this->data['geographygroupname']))?$this->data['geographygroupname']:"...",'Geography Region',(!empty($this->data['geographyregion']))?$this->data['geographyregion']:"...");
sapp_Helper::viewBody('nor','Currency',$this->data['currency'],'Geography City',(!empty($this->data['geographycityname']))?$this->data['geographycityname']:"...");
sapp_Helper::viewFooter();

?>

		<div class="new-form-ui-submit">
			<input type="submit" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
			<button onclick="window.location.href='<?php echo BASE_URL; ?>geographygroup';" type="button" >Cancel</button>
		</div>
  

<?php }?>   
</div> 