<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
 if (count($this->messages)) {?>
	<div id="dispmsgclients">
    <?php 
			foreach ($this->messages as $message)
			{
				$flag = array();				
				$flag = array_keys($message);
				echo "<div id='messageData' class='ml-alert-1-$flag[0]' style='margin-bottom: 0px;'><div style='display:block;'><span class='style-1-icon $flag[0]'></span>";
				echo $message[$flag[0]];
				echo "</div></div>";
			} 
	?>	
   </div> 
	
<?php } ?>
<span id="error_message"></span>
<?php 
 if($this->call == 'ajaxcall'){
	$div = ''; $endDiv = ''; 
} else { 
   ?>
    <div class="export-links">
      <div class="sprite export-xls" data-export="export" id="btnExport" >Export to Excel</div>

<?php

    $table = "<div id='exporttimesheet' class='details_data_display_block newtablegrid'><table id='timesheet' class='grid' width='100%' border='0' cellspacing='0' cellpadding='4' align='center'>
<thead><tr><th>Employee Id</th><th>Employee Name</th><th>Project Name</th><th>Task</th><th>Date</th><th>Day Name</th><th>Duration</th><th>Status</th></thead><tbody>";
    foreach ($this->dataArray[0][tablecontent] as $row)
    {
      $table .=  "<tr><td>".$row['employeeid']."</td><td>".$row['userfullname']."</td><td>".$row['project_name']."</td><td>".$row['task']."</td><td>".$row['Date1']."</td><td>".$row['DayName']."</td><td>".$row['Duration']."</td><td>".$row['Status']."</td>";
    }
    echo $table .="</tr></tbody></table>";// exit;
   
	}
?>
            <script src="<?php echo MEDIA_PATH;?>js/jquery.tabletoCSV.js"></script>

                    <script type='text/javascript'>
$(document).ready(function(){
<?php if($this->call != 'ajaxcall'){ ?>
	$('.breadcrumbs').append("<span class='arrows'>&rsaquo;</span><span>Timesheet</span>");
	<?php } ?>
<?php if (count($this->messages)) {?>
      setTimeout(function(){
			$('#dispmsgclients').fadeOut('slow');
		},3000);
<?php } ?>
   

$("#btnExport").click(function (e) {
      $("#timesheet").tableToCSV('timesheet');

  
}); 


});


</script>
