 <div class="form_cntr_block_80">

<?php if (count($this->messages)) {?>
	<div id="dispsyspref" class="settingssuccess">
		<?php 
			foreach ($this->messages as $message)
			{
				$flag = array();				
				$flag = array_keys($message);
				echo "<div id='messageData' class='ml-alert-1-$flag[0]'><div style='display:block;'><span class='style-1-icon $flag[0]'></span>";
				echo $message[$flag[0]];
				echo "</div></div>";
			} 
		?>
	</div>	
	
<?php } ?>
<span id="error_message"></span>



<?php if(empty($this->dataArray)){?>
	 <div class="ml-alert-1-info m1-info-set"><div class="style-1-icon info"></div>Identity codes are not yet set.
		<a href='<?php echo BASE_URL;?>identitycodes/add'>Click here</a>&nbsp; to add the identity codes.
	  </div>
<?php }else{?>

      <div class="edit-btn"><a href='<?php echo BASE_URL;?>identitycodes/edit/id/<?php echo $this->dataArray[0]['id']; ?>'>Edit</a></div>
<?php 
sapp_Helper::viewHeader();
sapp_Helper::viewBody('alt','Employee',(!empty( $this->dataArray[0]['employee_code']))? $this->dataArray[0]['employee_code']:"...",'Background Agency ',(!empty($this->dataArray[0]['backgroundagency_code']))?$this->dataArray[0]['backgroundagency_code']:"...");
sapp_Helper::viewBody('nor','Users',(!empty($this->dataArray[0]['users_code']))?$this->dataArray[0]['users_code']:"...",'Requisition',(!empty($this->dataArray[0]['requisition_code']))?$this->dataArray[0]['requisition_code']:"...");
sapp_Helper::viewBody('alt','Description',"Identitfication codes for different categories of people in an organization",'','');
sapp_Helper::viewFooter();
?>

	<?php } ?>

<script type='text/javascript'>
$(document).ready(function(){
<?php if (count($this->messages)) {?>
      setTimeout(function(){
			$('#dispsyspref').fadeOut('slow');
		},3000);

<?php } ?>

})
</script>
</div>