 

<script type="text/javascript" src="<?php echo MEDIA_PATH;?>js/candidate-details.js" /></script>
<?php
$candidate_details_view_helper = $this->candidatedetails(); 
$form = $this->form;
sapp_Global::generateClientValidations($this->form);
$tab_data = array('firstpoc','secondpoc','thirdpoc');
	
// To skip common elements in the form from validation (On both tab views - Upolad Resume && Update Candidate Details)
$msgarray = $candidate_details_view_helper->trimMessages($this->msgarray);
?>
<!-- 
	User can enter either of the following.
    1.Upload resume   
    2.Enter Candidate Details
    So the below form consists of two submit buttons for the above two options.  
-->
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="panel-title">Openings/Positions</div>
    </div>
<form class="form-horizontal" name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" method="POST" action='<?php echo $this->form->getAction();?>'>

<div class="panel-body nav-tabs-vertical"> 
   <div class="row">
	 <div class="form-group">
         <div class="col-md-6">
         <label class="col-md-3 control-label required">Requisition ID</label>
           <div class="col-md-9">
                <?php echo $form->requisition_id;?>
            </div>
            <?php if(isset($this->msgarray['requisition_id'])){?>
				   <span class="errors" id="errors-requisition_id"><?php echo $this->msgarray['requisition_id'];?></span>
		<?php }?>
    </div>
      <div class="col-md-6">
         <label class="col-md-3 control-label">Status</label>
         <div class="col-md-9"><select disabled class="form-control select"><option>Not Scheduled</option></select>
            <input type="hidden" value="Not Scheduled" name="cand_status" id="cand_status" />
        </div>
    </div> </div>
    <!--  <div class="new-form-ui inputheight-4">
        <label class="required">Candidate Name</label>
        <div class="division"><?php //echo $form->candidate_name; ?></div>
        <?php //if(isset($this->msgarray['candidate_name'])){?>
				   <span class="errors" id="errors-candidate_name"><?php //echo $this->msgarray['candidate_name'];?></span>
		<?php //}?>
    </div>-->
    <div class="form-group">
         <div class="col-md-6">
         <label class="col-md-3 control-label required">Candidate First Name</label>
        <div class="col-md-9"><?php echo $form->candidate_firstname; ?></div>
        <?php if(isset($this->msgarray['candidate_firstname'])){?>
				   <span class="errors" id="errors-candidate_firstname"><?php echo $this->msgarray['candidate_firstname'];?></span>
		<?php }?>
    </div>
    <div class="col-md-6">
         <label class="col-md-3 control-label">Candidate Last Name</label>
        <div class="col-md-9"><?php echo $form->candidate_lastname; ?></div>
        <?php if(isset($this->msgarray['candidate_lastname'])){?>
				   <span class="errors" id="errors-candidate_lastname"><?php echo $this->msgarray['candidate_lastname'];?></span>
		<?php }?>
    </div></div>
    <div class="form-group">
         <div class="col-md-6">
         <label class="col-md-3 control-label required">Email</label>
        <div class="col-md-9"><?php echo $form->emailid; ?></div>
       <?php if(isset($this->msgarray['emailid'])){?>
				   <span class="errors" id="errors-emailid"><?php echo $this->msgarray['emailid'];?></span>
		<?php }?>
    </div>
    
    <div class="col-md-6">
         <label class="col-md-3 control-label required">Contact Number</label>
        <div class="col-md-9"><?php echo $form->contact_number; ?></div>
		<?php if(isset($this->msgarray['contact_number'])){?>
				   <span class="errors" id="errors-contact_number"><?php echo $this->msgarray['contact_number'];?></span>
		<?php }?>
    </div></div>
    <div class="form-group">
         <div class="col-md-6">
         <label class="col-md-3 control-label required">Qualification</label>
        <div class="col-md-9"><?php echo $form->qualification; ?></div>
		<?php if(isset($this->msgarray['qualification'])){?>
				   <span class="errors" id="errors-qualification"><?php echo $this->msgarray['qualification'];?></span>
		<?php }?>
    </div></div>
    <div id="tabs" class="upload-link">
    	<a id="upload-resume" href="javascript:void(0);" <?php if($this->data['selected_option']=='upload-resume' || empty($this->data['selected_option'])){echo 'class="act"';}?>>Upload resume</a>&nbsp;&nbsp;&nbsp;(OR)&nbsp;&nbsp;&nbsp;<a id="candidate-form" href="javascript:void(0);" <?php if($this->data['selected_option']=='fill-up-form'){echo 'class="act"';}?>>Enter Candidate Details</a>
    </div>

    <div id='div-upload-resume' <?php $candidate_details_view_helper->checkViewResume($this->data, $msgarray);?> class="fltleft mrgetop20">
    	<div class="new-form-ui inputheight-4 fullwidth width450">
            <label class="required">Resume</label>
            <div class="division">
	            <span id='upload-file' class="uploadbut-resume upload_custom_div">Upload Resume</span> 
                <div id="loaderimg" style="display:none; clear:both; margin:0 auto; width:50px; position: absolute; left:165px; top:5px;"><img src="<?php echo $this->baseUrl("public/media/images/loaderwhite_21X21.gif");?>" style="width:21px; height: 21px; float: none; "/></div>
	            <span id='uploaded-file-name-span'><?php echo $this->data['cand_resume']; ?></span>
			    <input type="hidden" id="cand_resume" name="cand_resume" />
            </div>
        </div>
        <div class="new-form-ui-submit mrgetop30">
	    <div id='submit-button1'>
	        <?php echo $this->form->submit;?>
	    </div>  
       <div >
	        <button type="button" id="Cancel" name="Cancel" onclick="window.location.href='<?php echo BASE_URL; ?>candidatedetails';">Cancel</button>
	    </div>  
        </div>		
    </div>

    <div id='div-candidate-form' <?php $candidate_details_view_helper->checkViewForm($this->data, $msgarray);?> class="fltleft mrgetop20">

<!--	<div class="new-form-ui">
        <label class="required">Email</label>
        <div class="division"><?php//echo $form->emailid; ?></div>
		<?php //if(isset($this->msgarray['emailid'])){?>
				   <span class="errors" id="errors-emailid"><?php //echo $this->msgarray['emailid'];?></span>
		<?php //}?>
    </div>
    <div class="new-form-ui">
        <label class="required">Contact Number</label>
        <div class="division"><?php //echo $form->contact_number; ?></div>
		<?php //if(isset($this->msgarray['contact_number'])){?>
				   <span class="errors" id="errors-contact_number"><?php //echo $this->msgarray['contact_number'];?></span>
		<?php// }?>
    </div>
    <div class="new-form-ui">
        <label class="required">Qualification</label>
        <div class="division"><?php //echo $form->qualification; ?></div>
		<?php// if(isset($this->msgarray['qualification'])){?>
				   <span class="errors" id="errors-qualification"><?php //echo $this->msgarray['qualification'];?></span>
		<?php// }?>
    </div>-->
    <div class="form-group">
         <div class="col-md-6">
         <label class="col-md-3 control-label required">Work Experience <img class="tooltip" title="In years Ex : 4.5" src="<?php echo MEDIA_PATH;?>images/help.png"></label>
        <div class="col-md-9"><?php echo $form->experience; ?></div>
		<?php if(isset($this->msgarray['experience'])){?>
				   <span class="errors" id="errors-experience"><?php echo $this->msgarray['experience'];?></span>
		<?php }?>
    </div>
    <div class="col-md-6">
         <label class="col-md-3 control-label required">Skill Set</label>
        <div class="col-md-9"><?php echo $form->skillset; ?></div>
		<?php if(isset($this->msgarray['skillset'])){?>
				   <span class="errors" id="errors-skillset"><?php echo $this->msgarray['skillset'];?></span>
		<?php }?>
    </div></div>
    <div class="form-group">
         <div class="col-md-6">
         <label class="col-md-3 control-label">Education Summary</label>
        <div class="col-md-9"><?php echo $form->education_summary; ?></div>
    </div>
    <div class="col-md-6">
         <label class="col-md-3 control-label">Summary</label>
        <div class="col-md-9"><?php echo $form->summary; ?></div>
    </div></div>
    <div class="form-group">
         <div class="col-md-6">
         <label class="col-md-3 control-label required">Location</label>
        <div class="col-md-9"><?php echo $form->cand_location; ?></div>
		<?php if(isset($this->msgarray['cand_location'])){?>
				   <span class="errors" id="errors-cand_location"><?php echo $this->msgarray['cand_location'];?></span>
		<?php }?>
    </div>
     
         <div class="col-md-6">
         <label class="col-md-3 control-label required">Country</label>
        <div class="col-md-9"><?php echo $form->country; ?>
		<?php if(isset($this->msgarray['country'])){?>
				   <span class="errors" id="errors-country"><?php echo $this->msgarray['country'];?></span>
		<?php }?>
        <?php if(in_array('country',$this->popConfigPermission)) { ?>	
			<span class="add-coloum" onclick="displaydeptform('<?php echo BASE_URL.'countries/addnewcountry' ?>','Country');"> Add Country</span>			
		<?php } ?>
        </div>
    </div></div>
    <div class="form-group">
         <div class="col-md-6">
         <label class="col-md-3 control-label required">State</label>
        <div class="col-md-9"><?php echo $form->state; ?>
		<?php if(isset($this->msgarray['state'])){?>
				   <span class="errors" id="errors-state"><?php echo $this->msgarray['state'];?></span>
		<?php }?>
        <?php if(in_array('state',$this->popConfigPermission)) { ?>	
			<span class="add-coloum" onclick="displaydeptform('<?php echo BASE_URL.'states/addnewstate' ?>','State');"> Add State</span>			
		<?php } ?>
        </div>
    </div>
    <div class="col-md-6">
         <label class="col-md-3 control-label required">City</label>
        <div class="col-md-9"><?php echo $form->city; ?>
		<?php if(isset($this->msgarray['city'])){?>
				   <span class="errors" id="errors-city"><?php echo $this->msgarray['city'];?></span>
		<?php }?>
        <?php if(in_array('city',$this->popConfigPermission)) { ?>	
			<span class="add-coloum" onclick="displaydeptform('<?php echo BASE_URL.'cities/addnewcity' ?>','City');"> Add City</span>			
		<?php } ?>
        </div>
    </div></div>
	 <div class="form-group">
         <div class="col-md-6">
         <label class="col-md-3 control-label required">Postal Code</label>
        <div class="col-md-9"><?php echo $form->pincode; ?></div>
		<?php if(isset($this->msgarray['pincode'])){?>
				   <span class="errors" id="errors-pincode"><?php echo $this->msgarray['pincode'];?></span>
		<?php }?>
    </div>  </div> 
    <div class="separetor-heading"><h3>Previous Company Details</h3></div>        
    <div class="tabs">
                <ul class="nav nav-tabs">
                    <li class="tab-pane active" id="poclifirst" style="cursor:pointer;"><a href="#" onclick="contactElements('first');">Company 1</a></li>
                    <li class="tab-pane" id="poclisecond" style="cursor:pointer;"><a href="#" onclick="contactElements('second');">Company 2</a></li>
                    <li class="tab-pane" id="poclithird" style="cursor:pointer;"><a href="#" onclick="contactElements('third');">Company 3</a></li>
                </ul>


        <div class="tab-content panel-body">		
<?php 

          foreach($tab_data as $key => $value)
          {       
              
              $company_name = "txt_cname$key";
              $designation = "txt_desig".$key;
              $from_date = "txt_from".$key;
              $to_date = "txt_to".$key;
              $contact_number = "txt_cnumber".$key;
              $website = "txt_website".$key;
              $comp_address = "txt_address".$key;
?>              
            <div id="<?php echo $value;?>" class="clearb fltleft">
                
                <div class="form-group">
         <div class="col-md-6">
         <label class="col-md-3 control-label required">Company Name</label>
                <div class="col-md-9"><?php echo $form->$company_name;?>
                   <?php if(isset($this->msgarray[$company_name])){?>
                           <span class="errors" id="errors-idtxt_cname<?php echo $key; ?>"><?php echo $this->msgarray[$company_name];?></span>
                  <?php }?>
                </div></div>

                <div class="col-md-6">
         <label class="col-md-3 control-label">Designation</label>
               <div class="col-md-9"><?php echo $form->$designation;?>
                  <?php if(isset($this->msgarray[$designation])){?>
                           <span class="errors" id="errors-idtxt_desig<?php echo $key; ?>"><?php echo $this->msgarray[$designation];?></span>
                  <?php }?>
                </div> </div></div>	

                 <div class="form-group">
         <div class="col-md-6">
         <label class="col-md-3 control-label">From <img class="tooltip" title="<?php echo DATE_DESCRIPTION;?>" src="<?php echo MEDIA_PATH;?>images/help.png"></label>
                <div class="col-md-9"><?php echo $form->$from_date;?>
                 <?php if(isset($this->msgarray[$from_date])){?>
                           <span class="errors" id="errors-idtxt_from<?php echo $key;?>"><?php echo $this->msgarray[$from_date];?></span>
                  <?php }?>
                </div></div>

                <div class="col-md-6">
         <label class="col-md-3 control-label">To <img class="tooltip" title="<?php echo DATE_DESCRIPTION;?>" src="<?php echo MEDIA_PATH;?>images/help.png"></label>
                <div class="col-md-9"><?php echo $form->$to_date;?>
                   <?php if(isset($this->msgarray[$to_date])){?>
                           <span class="errors" id="errors-idtxt_to<?php echo $key;?>"><?php echo $this->msgarray[$to_date];?></span>
                  <?php }?>
                </div>	</div>	
                     </div>	

                 <div class="form-group">
         <div class="col-md-6">
         <label class="col-md-3 control-label">Contact Number</label>
                <div class="col-md-9"><?php echo $form->$contact_number;?>
                   <?php if(isset($this->msgarray[$contact_number])){?>
                           <span class="errors" id="errors-idtxt_cnumber<?php echo $key;?>"><?php echo $this->msgarray[$contact_number];?></span>
                  <?php }?>
                </div></div>

                <div class="col-md-6">
         <label class="col-md-3 control-label">Web site</label>
                <div class="col-md-9"><?php echo $form->$website;?>
                   <?php if(isset($this->msgarray[$website])){?>
                           <span class="errors" id="errors-idtxt_website<?php echo $key;?>"><?php echo $this->msgarray[$website];?></span>
                  <?php }?>
                </div></div>
                 </div>
                <div class="form-group">
         <div class="col-md-6">
         <label class="col-md-3 control-label"> Address</label>
                <div class="col-md-9"><?php echo $form->$comp_address;?>
                   <?php if(isset($this->msgarray[$comp_address])){?>
                           <span class="errors" id="errors-idtxt_address<?php echo $key;?>"><?php echo $this->msgarray[$comp_address];?></span>
                  <?php }?>
                </div></div></div>
            </div>
<?php             
          }
?>                    
                    </div>
     </div></div>

	    <div id='submit-button2' class="panel-footer">
	        <?php echo $this->form->submit;?>
                <button type="button" id="Cancel" class="btn btn-danger" name="Cancel" onclick="window.location.href='<?php echo BASE_URL; ?>candidatedetails';">Cancel</button>
	    </div>
	</div>
   	<input type="hidden" id='selected_option' name='selected_option' value="<?php $candidate_details_view_helper->checkSelectedOption($this->data);?>" />
</div>    </div>    
</form></div>

    <div id="countriesContainer"  style="display: none; overflow: auto;">
		<div class="heading">
			<a href="javascript:void(0)">
			<img src="<?php echo $this->baseUrl().'/public/media/';?>images/close.png" name="" align="right"
				border="0" hspace="3" vspace="5" class="closeAttachPopup"
				style="margin: -24px 8px 0 0;"> </a>
		</div>

			<iframe id="countriesCont" class="business_units_iframe" frameborder="0"></iframe>

	</div>
	
	<div id="statesContainer"  style="display: none; overflow: auto;">
		<div class="heading">
			<a href="javascript:void(0)">
			<img src="<?php echo $this->baseUrl().'/public/media/';?>images/close.png" name="" align="right" border="0" hspace="3" vspace="5" class="closeAttachPopup" style="margin: -24px 8px 0 0;"> </a>
		</div>

		<iframe id="statesCont" class="business_units_iframe" frameborder="0"></iframe>
	</div>  

	<div id="citiesContainer"  style="display: none; overflow: auto;">
		<div class="heading">
			<a href="javascript:void(0)">
			<img src="<?php echo $this->baseUrl().'/public/media/';?>images/close.png" name="" align="right" border="0" hspace="3" vspace="5" class="closeAttachPopup" style="margin: -24px 8px 0 0;"> </a>
		</div>

		<iframe id="citiesCont" class="business_units_iframe" frameborder="0"></iframe>
	</div> 
<script type="text/javascript" language="javascript">
var yearrange = <?php echo "'".YEAR.':'.date('Y')."'"; ?>;
$(document).ready(function(){
    $("#secondpoc,#thirdpoc").hide();
<?php 
    foreach($tab_data as $key => $value)
    {              
?>  
    $( "#idtxt_from<?php echo $key;?>,#idtxt_to<?php echo $key;?>" ).datepicker({
        showOn: "both",
        buttonImage: "<?php echo MEDIA_PATH;?>images/cal.png",
        buttonImageOnly: true,
        buttonText: "",
        yearRange: yearrange,
        maxDate:0,
        changeMonth: true,
        changeYear: true,
        dateFormat:"<?php echo DATEFORMAT_JS;?>",
        showButtonPanel: true ,
        onClose:function()
        {
            var patt1=new RegExp("idtxt_from");  
            var msg = '';
            if(patt1.test(this.id))            
                msg = "From date should be less than to date.";                    
            else                 
                msg = "To date should be greater than from date.";        
            from_to_date_validation('idtxt_from<?php echo $key;?>','idtxt_to<?php echo $key;?>',this,msg);
        }
    });
<?php 
    }
?>
    var complete_width = $('.poc-ui-data-control').width();
    $('.left-block-ui-data').css("width", "230");
    $('.right-block-data').css("width", (complete_width-(253)));	
		
    function checkWidth() 
    {
        var complete_width = $('.poc-ui-data-control').width();		
        $('.left-block-ui-data').css("width", "230");
        $('.right-block-data').css("width", (complete_width-(253)));		
    }
    $(window).resize(function() {
        checkWidth();
    });
    
    $('#submit-button2').click(function(){
        $('.errors').remove();    
        
        var ele_arr = new Array('idtxt_cname','idtxt_desig','idtxt_from','idtxt_to',
                                'idtxt_cnumber','idtxt_website','idtxt_address');
        var validation_err = new Array('Please enter company name.','Please enter designation.',
                                       'Please enter from date.','Please enter to date.',
                                       'Please enter contact number.','Please enter website.',
                                       'Please enter address.');                        
        var tab_data = new Array('first','second','third');
        var s = 0;
        for(var i=0;i<3;i++)
        {
            var k = 0;
            for(var j=0;j<ele_arr.length;j++)
            {
                var val = $('#'+ele_arr[j]+i).val();
                if(val == '')
                    k++;                                
            }
            if(k != ele_arr.length && k!= 0)
            {
                s++;  
                        
                for(var j=0;j<ele_arr.length;j++)
                {
                    var val = $('#'+ele_arr[j]+i).val();
                    if(val == '')
                    {
                        $("#errors-"+ele_arr[j]+i).remove();                    
                        $('#'+ele_arr[j]+i).parent().append("<span class='errors' id='errors-"+ele_arr[j]+i+"'>"+validation_err[j]+"</span>");
                    }
                }
                contactElements(tab_data[i]);
                
            }
        }
        if(s == 0)
            return true;
        else 
        {
            $.unblockUI();
            return false;
        }
    });
    
});//end of ready function
</script>