 

<?php if($this->ermsg == 'nodata') { ?>
<div class="ml-alert-1-info"><div class="style-1-icon info"></div>No data found.</div>
<?php }else {?>
<?php if (count($this->messages)) 
{?>
	<div id="dispscreeningtype" class="settingssuccess">
		<?php 
			foreach ($this->messages as $message)
			{
				$flag = array();				
				$flag = array_keys($message);
				echo "<div id='messageData' class='ml-alert-1-$flag[0]'><div style='display:block;'><span class='style-1-icon $flag[0]'></span>";
				echo $message[$flag[0]];
				echo "</div></div>";
			} 
		?>
	</div>	
	
<?php } 
if($this->call != 'ajaxcall'){
if(sapp_Global::_isactivemodule(RESOURCEREQUISITION)){
?>
<!--<div class="form_cntr_single">
<div class="total-form-controller">
    <div class="new-form-ui inputheight-3"> 
        <div class="division"><select id="statusid" name="statusid" class="select2-offscreen" tabindex="-1" onchange = "displayStatusdata('empscreening')">
            <option value="<?php //echo sapp_Global::_encrypt(2);?>">Candidates</option>
			<option value="<?php //echo sapp_Global::_encrypt(1);?>">Employees</option>
			                       
            </select>
        </div>
    </div>
</div></div>-->
<?php 
} } ?>
<span id="error_message" class="fltleft fullwidth"></span>
<?php 

if($this->call == 'ajaxcall'){
	$div = ''; $endDiv = ''; 
} else { 
	$div = '<div id="grid_'.$this->dataArray[0]['objectname'].'" class="all-grid-control">'; $endDiv = '</div>';
}
	echo $div.'<div id="msg" style="display:none;font-style: oblique; font-weight: bold; color: green;""></div>'.$this->grid($this->dataArray[0]).$endDiv;
        
?>
<div id="table"></div>

<script type='text/javascript'>
$(document).ready(function(){
    $(".table").hide();
    $(".table-btm").hide();
    $.post(base_url + "/index/onboardingcandidates", {}, function (data) {
        $("#table").html(data);
    });
    
    $(".addrecord").hide();
<?php if (count($this->messages)) {?>
      setTimeout(function(){
			$('#dispmsgncc').fadeOut('slow');
		},3000);

<?php } ?>

})
<?php if($this->statusidstring !=''){ ?>
       $('#statusid').val('<?php echo $this->statusidstring; ?>');
<?php }else {?>
		$('#statusid').val('<?php echo sapp_Global::_encrypt(1); ?>');
<?php } ?>
</script>
<?php } ?>
