 <div class="form_cntr_block">
<?php 	
if($this->ermsg !='')
{
?>
     <div class="ml-alert-1-info m1-info-set"><div class="style-1-icon info"></div>No data found.</div>
<?php 
}
else
{
$baseUrl = $this->serverUrl().$this->baseUrl();
echo $this->form->id; ?>
 <?php 
sapp_Helper::viewHeader();
sapp_Helper::viewBody('nor','Attendance Status',$this->data['attendancestatuscode'],'Description',(!empty($this->data['description']))?$this->data['description']:"...");
sapp_Helper::viewFooter();
?>

       <!--  <div class="total-form-controller view-form-detail">
			<div class="new-form-ui clearb">
			  <label>Attendance Status</label>
			<div class="division"><?php echo $this->form->attendancestatuscode; ?></div>
			</div>	
			<div class="new-form-ui clearb textareaheight">
			  <label>Description</label>
			<div class="division"><?php echo $this->form->description; ?></div>
			</div> -->
		<div class="new-form-ui-submit">
			<input type="submit" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />			
			<button onclick="window.location.href='<?php echo BASE_URL; ?>attendancestatuscode';" type="button" >Cancel</button>
		</div>
      
<?php	}	?> 
</div>