<div class="col-md-3 col-sm-4 col-xs-5">
<!--    --><?php //print_r($this->email); exit; ?>
  <form action="#" class="form-horizontal">
    <div class="panel panel-default">
      <div class="panel-body">
        <h3>
          <span class="fa fa-user"></span> John Doe
        </h3>
        <p> <?php echo $this->jobtitle; ?>/ <?php echo $this->position; ?></p>
        <div class="text-center" id="user_image">
          <img src="assets/images/users/user2.jpg" class="img-thumbnail">
                                    </div>
      </div>
      <div class="panel-body form-group-separated">

        <div class="form-group">
          <div class="col-md-12 col-xs-12">
            <a href="#" class="btn btn-primary btn-block btn-rounded" data-toggle="modal" data-target="#modal_change_photo">Change Photo</a>
          </div>
        </div>

        <div class="form-group">
          <label class="col-md-3 col-xs-5 control-label">#ID</label>
          <div class="col-md-9 col-xs-7">
            <?php echo $this->form->employeeId; ?>
                                        </div>
        </div>

        <div class="form-group">
          <label class="col-md-3 col-xs-5 control-label">Login</label>
          <div class="col-md-9 col-xs-7">
            <?php echo $this->form->emailaddress; ?>
                                        </div>
        </div>

        <div class="form-group">
          <label class="col-md-3 col-xs-5 control-label">E-mail</label>
          <div class="col-md-9 col-xs-7">
            <?php echo $this->form->emailaddress; ?>
                                        </div>
        </div>

        <div class="form-group">
          <div class="col-md-12 col-xs-12">
            <a href="#" class="btn btn-danger btn-block btn-rounded" data-toggle="modal" data-target="#modal_change_password">Change password</a>
          </div>
        </div>

      </div>
    </div>
  </form>

</div>
<div class="col-md-6 col-sm-8 col-xs-7">

    <form name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction();?>" method="<?php echo $this->form->getMethod(); ?>">
        <?php echo $this->form->id;
        echo $this->form->emptyFlag;
        ?>
    <div class="panel panel-default">
      <div class="panel-body">
        <h3>
          <span class="fa fa-pencil"></span> Profile
        </h3>
        <p>This information lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus, est quis molestie tincidunt, elit arcu faucibus erat.</p>
      </div>

      <div class="panel-body form-group-separated">
        <div class="form-group">
          <label class="col-md-3 col-xs-5 control-label">First Name</label>
          <div class="col-md-9 col-xs-7">
            <?php echo $this->form->firstname; ?>
            <!--<input value="<?php echo $this->form->firstname; ?>" class="form-control" type="text">-->
                                        </div>
        </div>
        <div class="form-group">
          <label class="col-md-3 col-xs-5 control-label">Last Name</label>
          <div class="col-md-9 col-xs-7">
            <?php echo $this->form->lastname; ?>
                                        </div>
        </div>
        <div class="form-group">
          <label class="col-md-3 col-xs-5 control-label">Location</label>
          <div class="col-md-9 col-xs-7">
            <?php echo $this->form->location; ?>
                                        </div>
        </div>
        <div class="form-group">
          <label class="col-md-3 col-xs-5 control-label">About me</label>
          <div class="col-md-9 col-xs-7">
            <?php echo $this->form->aboutme; ?>
            
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-12 col-xs-5">
            <button class="btn btn-primary btn-rounded pull-left">More</button>
<!--            <button class="btn btn-primary btn-rounded pull-right">Save</button>-->
              <?php echo $this->form->submit; ?>
          </div>
        </div>
      </div>
    </div>
    </form>

  <div class="panel panel-default tabs">
    <ul class="nav nav-tabs">
      <li class="active">
        <a href="#tab1" data-toggle="tab">Contacts</a>
      </li>
      <li>
        <a href="#tab2" data-toggle="tab">Send Message</a>
      </li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane panel-body active" id="tab1">

        <div class="list-group list-group-contacts border-bottom">
          <a href="#" class="list-group-item">
            <div class="list-group-status status-online"></div>
            <img src="assets/images/users/user3.jpg" class="pull-left" alt="Nadia Ali">
              <span class="contacts-title">Nadia Ali</span>
              <p>Singer-Songwriter</p>
              <div class="list-group-controls">
                <button class="btn btn-primary btn-rounded">
                  <span class="fa fa-pencil"></span>
                </button>
              </div>
            </a>
          <a href="#" class="list-group-item">
            <div class="list-group-status status-online"></div>
            <img src="assets/images/users/user.jpg" class="pull-left" alt="Dmitry Ivaniuk">
              <span class="contacts-title">Dmitry Ivaniuk</span>
              <p>Web Developer/Designer</p>
              <div class="list-group-controls">
                <button class="btn btn-primary btn-rounded">
                  <span class="fa fa-pencil"></span>
                </button>
              </div>
            </a>
          <a href="#" class="list-group-item">
            <div class="list-group-status status-away"></div>
            <img src="assets/images/users/user2.jpg" class="pull-left" alt="John Doe">
              <span class="contacts-title">John Doe</span>
              <p>UI/UX Designer</p>
              <div class="list-group-controls">
                <button class="btn btn-primary btn-rounded">
                  <span class="fa fa-pencil"></span>
                </button>
              </div>
            </a>
        </div>

      </div>
      <div class="tab-pane panel-body" id="tab2">
        <p>Feel free to contact us for any issues you might have with our products.</p>
        <div class="form-group">
          <label>E-mail</label>
          <input class="form-control" placeholder="youremail@domain.com" type="email">
                                        </div>
        <div class="form-group">
          <label>Subject</label>
          <input class="form-control" placeholder="Message subject" type="email">
                                        </div>
        <div class="form-group">
          <label>Message</label>
          <textarea class="form-control" placeholder="Your message" rows="3"></textarea>
        </div>
      </div>

    </div>

  </div>

</div>

<div class="col-md-3">
  <div class="panel panel-default form-horizontal">
    <div class="panel-body">
      <h3>
        <span class="fa fa-info-circle"></span> Quick Info
      </h3>
      <p>Some quick info about this user</p>
    </div>
    <div class="panel-body form-group-separated">
      <div class="form-group">

        <label class="col-md-4 col-xs-5 control-label">Last visit</label>
        <div class="col-md-8 col-xs-7 line-height-30"><?php echo $this->logindatetime; ?></div>
      </div>
      <div class="form-group">
        <label class="col-md-4 col-xs-5 control-label">Registration</label>
        <div class="col-md-8 col-xs-7 line-height-30"><?php echo $this->registerdate; ?></div>
      </div>
      <div class="form-group">
        <label class="col-md-4 col-xs-5 control-label">Groups</label>
        <div class="col-md-8 col-xs-7">administrators, managers, team-leaders, developers</div>
      </div>
      <div class="form-group">
        <label class="col-md-4 col-xs-5 control-label">Birthday</label>
        <div class="col-md-8 col-xs-7 line-height-30"><?php echo $this->dob; ?></div>
      </div>
    </div>

  </div>

  <div class="panel panel-default">
    <div class="panel-body">
      <h3>
        <span class="fa fa-cog"></span> Settings
      </h3>
      <p>Sample of settings block</p>
    </div>
    <div class="panel-body form-horizontal form-group-separated">
      <div class="form-group">
        <label class="col-md-6 col-xs-6 control-label">Notifications</label>
        <div class="col-md-6 col-xs-6">
          <label class="switch">
            <input checked="" value="1" type="checkbox">
              <span></span>
            </label>
        </div>
      </div>
      <div class="form-group">
        <label class="col-md-6 col-xs-6 control-label">Mailing</label>
        <div class="col-md-6 col-xs-6">
          <label class="switch">
            <input checked="" value="1" type="checkbox">
              <span></span>
            </label>
        </div>
      </div>
      <div class="form-group">
        <label class="col-md-6 col-xs-6 control-label">Priority</label>
        <div class="col-md-6 col-xs-6">
          <label class="switch">
            <input value="0" type="checkbox">
              <span></span>
            </label>
        </div>
      </div>
    </div>
  </div>
</div>


<!--<?php

$login_user_role = $this->login_user_role;
?>
<script type="text/javascript">
$(document).ready(function(){	

		<?php if (count($this->messages)) {?>
		$("#error_message").css('display','block');
		      setTimeout(function(){
					$('#dispmsgprofile').fadeOut('slow');
				},3000);
<?php }?>

	var total_width = $('.profile-tabs').width();
	var profile_tabs_right_password_width = total_width-2;	
	$('.profile-tabs-left').css("width", "150");
	$('.profile-tabs-right').css("width", (profile_tabs_right_password_width-155));
	
	function checkWidth() {
        var total_width = $('.profile-tabs').width();
		var profile_tabs_right_password_width = total_width-2;		
		$('.profile-tabs-left').css("width", "150");
		$('.profile-tabs-right').css("width", (profile_tabs_right_password_width-155));        
    }
	
	$(window).resize(function() {
		checkWidth();
	});
});
</script>


<div id="error_message"  >
<?php if (count($this->messages)) {?>
	<div id="dispmsgprofile">
	<div class="ml-alert-1-success">
	<div class="style-1-icon success"></div>
		<?php foreach ($this->messages as $message){?>
		 <?php echo $this->escape($message); ?>
		<?php } ?>
        </div>	
	</div>	
	
<?php } ?>

</div>
<div class="profile-tabs">
    <div class="profile-tabs-left">
        <ul>
            <li class="now"><div class="profile-icon view-profile-hover"></div><p>View Profile</p><div class="absolute-div"></div></li>
            <li><a href="<?php echo BASE_URL; ?>viewsettings/1"><div class="profile-icon view-settings"></div><p>Settings</p></a></li>
            <li><a href="<?php echo BASE_URL; ?>dashboard/changepassword"><div class="profile-icon view-password"></div><p>Change Password</p></a></li>
            <?php 
            if($login_user_role == SUPERADMINROLE)
            {
            ?>
            <li><a href="<?php echo BASE_URL; ?>dashboard/emailsettings"><div class="profile-icon view-emailsettings"></div><p>Mail Settings</p></a></li>
            <?php 
            }
            ?>
        </ul>

            <input type="hidden" id="userid" value="<?php echo $this->id;?>"/>
    </div>


<div class="profile-tabs-right">

<div class="profile-tabs-right-inside">
    <div class="profile-tabs-right-1">
    <?php if($this->role == 'true' && $this->role !=''){
    sapp_Global::generateClientValidations($this->form);
    ?>
			    <form name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction();?>" method="<?php echo $this->form->getMethod(); ?>">
					<?php echo $this->form->id; 
						echo $this->form->emptyFlag; 
					?>
			        <div class="total-form-controller">
					    --><!--  <div class="new-form-ui">
						  <label class="required"><?php //echo $this->form->userfullname->getLabel();?></label>
						<div class="division"><?php //echo $this->form->userfullname; ?></div>
						<?php //if(isset($this->msgarray['userfullname'])){?>
						   <span class="errors" id="errors-<?php //echo $this->form->userfullname->getId(); ?>"><?php //echo $this->msgarray['userfullname'];?></span>
						<?php //}?>
						</div>--><!--
						
						<div class="new-form-ui">
						  <label class="required"><?php echo $this->form->firstname->getLabel();?></label>
						<div class="division"><?php echo $this->form->firstname; ?></div>
						<?php if(isset($this->msgarray['firstname'])){?>
						   <span class="errors" id="errors-<?php echo $this->form->firstname->getId(); ?>"><?php echo $this->msgarray['firstname'];?></span>
						<?php }?>
						</div>
						
						<div class="new-form-ui">
						  <label class="required"><?php echo $this->form->lastname->getLabel();?></label>
						<div class="division"><?php echo $this->form->lastname; ?></div>
						<?php if(isset($this->msgarray['lastname'])){?>
						   <span class="errors" id="errors-<?php echo $this->form->lastname->getId(); ?>"><?php echo $this->msgarray['lastname'];?></span>
						<?php }?>
						</div>
						
						<div class="new-form-ui">
						  <label class="required"><?php echo $this->form->emailaddress->getLabel();?></label>
						<div class="division"><?php echo $this->form->emailaddress; ?></div>
						<?php if(isset($this->msgarray['emailaddress'])){?>
						   <span class="errors" id="errors-<?php echo $this->form->emailaddress->getId(); ?>"><?php echo $this->msgarray['emailaddress'];?></span>
						<?php }?>
						</div>
				
					<div class="new-form-ui-submit">
					<?php echo $this->form->submit; ?>
					</div>
			</div>
			</form>
		<?php }else{?>	
        <ul>
        --><!--  <li><label>User Name</label><span><?php //echo $this->username;?></span></li>--><!--
        <li><label>First Name</label><span><?php echo $this->firstname;?></span></li>
        <li><label>Last Name</label><span><?php echo $this->lastname;?></span></li>        	
        <li><label>Email</label><span><?php echo $this->email;?></span></li>                                                
        </ul>
        <?php }?>			
    </div>
	
	--><!-- For Photo Upload --><!--
	<div class="profile-tabs-right-2">
    		<div class="change-profile-pic-div">
            	<div class="chg-img">
				   <?php  if($this->profileimage!=''){?>
							<img id="blah" class="imgbrdr" style="padding:0px;" src="<?php echo DOMAIN; ?>public/uploads/profile/<?php echo $this->profileimage; ?>" onerror="this.src='<?php echo MEDIA_PATH; ?>images/default-profile-pic.jpg'"/>
					<?php }
					else{?>
							<img id="blah" class="imgbrdr"  src="<?php echo MEDIA_PATH;?>images/default-profile-pic.jpg" />
					<?php }?> 
				
				</div>
            	
				
							<div class="left_div" >
								<span class="uploadbut uploadbutsel" id="upload_custom_div"> Upload Your Photo</span>
								<div id="loaderimgprofile" style="display:none;"><img src="<?php echo DOMAIN; ?>public/media/images/loaderwhite_21X21.gif" style="width:21px; height: 21px; float: none; "/></div>
								
							</div> 
                
	--><!-- Start Div for updating photoupload--><!--
   			  <div id="profile_add" style="display:none; margin: 0 auto; width: 80px;">
					<div class="mrgetop10 fltleft"><input type="button" class="submit_bg" value="Update" onclick="profileImageSave();" /></div>
 			</div>
	--><!--End Update div --><!--	
				
            </div>
					    <input type="hidden" id="uploadimagepath" name="uploadimagepath" value="<?php echo $this->profileimage;?>"/>
						<input type="hidden" name="profile_photo" value=""/>
							
	--><!-- End Photo Upload --><!--
	
              <div class="uploaderror_profile" style="display:none;"></div>
	           				                        					
       </div>
</div>
</div>
</div>


<script type="text/javascript">

var btnUpload = $('#upload_custom_div');
new AjaxUpload(btnUpload, {

	action :  base_url+'/dashboard/uploadpreview',
	name   : 'profile_photo',  //we can rename it 
	dataType: 'json',
	onSubmit: function(file,ext){
	if($(".uploaderror_profile").is(":visible"))
	 $(".uploaderror_profile").hide();
	  $("#loaderimgprofile").show();
									 
	},
	onComplete: function(file, response){
	    var result = JSON.parse(response);
      	if(result.result == 'success')
		{
		    
			$('.chg-img').show();
			$("#uploadimagepath").val(result.img);
			$('.chg-img').html('<img src="<?php echo DOMAIN; ?>public/uploads/preview/'+result.img+'" width="50" height="50"/>');
			$("#profile_add").show();
			$("#loaderimgprofile").hide();
		}
		else
		{
			$('.uploaderror_profile').show();
			if(result.msg)
			 $('.uploaderror_profile').html(result.msg);
			else
             $('.uploaderror_profile').html("Please choose different file."); 			
			$("#loaderimgprofile").hide();
			setTimeout(function()
			{
			$('.uploaderror_profile').fadeOut('slow');
			},3000);
		}
	}	
},'json');
</script>-->