<?php
/* * ******************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 * ****************************************************************************** */


if ($this->ermsg != '') {
    ?>
    <div class="ml-alert-1-info m1-info-set"><div class="style-1-icon info"></div>No data found.</div>
<?php
} else {
    sapp_Global::generateClientValidations($this->form);
    $request = Zend_Controller_Front::getInstance();
    $actionName = $request->getRequest()->getActionName();
    if ($actionName == 'view')
        $viewclass = 'view-form-detail';
    else
        $viewclass = '';

    $departmentArr = array();
    if (!empty($this->popConfigPermission)) {
        if (in_array('appraisalcategories', $this->popConfigPermission)) {

            $departmentArr['popup_url'] = 'appraisalcategory/addpopup';
            $departmentArr['popup_disp_name'] = 'Parameter';
            $departmentArr['popup_link_name'] = 'Add Parameter';
        }
    }
    ?>
    <div id="error_message" style="display:none;"></div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-title">Parameters</div>
        </div>
        <form  class="form-horizontal" name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>">

    <?php echo $this->form->id; ?>
    <?php echo $viewclass; ?>
              <div class="panel-body">            
                <div class="col-md-6">	
            <?php echo sapp_Helper::sd_form_helper($this->msgarray, $this->form, 'pa_category_id', '', '', 'required', $departmentArr); ?>
          		
                    <div id="multi_dept_div">
    <?php if (!$_POST) { ?>
                            <div id='parent_0' class="add_request" >
                                <div class="form-group">
                                    <label class="col-md-3 control-label required">Question <img class="tooltip" title="Special characters allowed are - ? ' . , / # @ $ & * ( ) !" src="<?php echo $this->baseUrl() . '/public/media/'; ?>images/help.png"></label>
                                    <div class="col-md-9">
                                        <input type="text" maxlength="100" value="" id="question_0" name="question[]" class='form-control cls_service_request_name' onblur='validatequestionname(this)' onkeyup='validatequestionname(this)'>                            
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-3 control-label">Description </label>
                                    <div class="col-md-9">
                                        <textarea maxlength="400" cols="30" rows="4" id="description_0" name="description[]" class="form-control" ></textarea>
                                    </div>
                                </div>
                            </div>
                            <span id="add-candidate"><span class="sprite candidate-new" onclick="addAppQuestionDiv()">Add New Question</span></span>
    <?php } ?>

                    </div>

                    <input type="hidden" value="0" id="idcount"/>	

                    <span id="errors-maxdiv" class="errors"></span>		

                </div></div>
            <div class="panel-footer">
    <?php echo $this->form->submitbutton; ?>
    <?php if ($actionName == 'view') { ?>
                    <input type="button" onclick="changeeditscreen('<?php echo $this->controllername; ?>',<?php echo $this->id; ?>);" value="Edit" />
                <?php } ?>
                <button onclick="window.location.href = '<?php echo BASE_URL; ?>appraisalquestions';" type="button" id="Cancel" class="btn btn-danger" name="Cancel">Cancel</button>
            </div>

        </form></div>

    <?php echo sapp_Helper::popup_helper('appraisalcategory'); ?>

<?php } ?>


<script type="text/javascript">

    function validatequestiononsubmit(ele)
    {
        var parentdivlength = $('div[id^=parent]').length;
        var re = /^[a-zA-Z0-9\- ?'.,\/#@$&*()!]+$/;
        var errorcount = 0;
        var categoryid = $('#pa_category_id').val();
        $('#errors-pa_category_id').remove();
        var values = $("input[name='service_request_name\\[\\]']").map(function () {
            return $(this).val();
        }).get();
        if (parentdivlength > 0)
        {
            $('.add_request').each(function (i) {
                var ele = $(this).find('.cls_service_request_name');
                var elementid = $(ele).attr('id');

                var reqValue = $(ele).val();
                $('#errors-' + elementid).remove();
                if ($(ele).val() == '')
                {
                    $(ele).parent().append("<span class='errors' id='errors-" + elementid + "'>Please enter question.</span>");
                    errorcount++;
                } else if (!re.test(reqValue))
                {
                    $(ele).parent().append("<span class='errors' id='errors-" + elementid + "'>Please enter valid question.</span>");
                    errorcount++;
                } else
                {
                    $('#errors-' + elementid).remove();
                }
            });
        }
        if (categoryid == '')
        {
            $('#pa_category_id').after("<span class='errors' id='errors-pa_category_id'>Please select parameter.</span>");
        } else
        {
            $('#errors-pa_category_id').remove();
        }

        if (errorcount == 0 && categoryid != '')
        {
            $.blockUI({width: '50px', message: $("#spinner").html()});
            document.getElementById("formid").submit();
        }
    }


    $(document).ready(function () {
        $("[id^=description]").maxlength();
        var counter = 0;
<?php
if ($_POST) {
    if (isset($this->msgarray['requestsize'])) {
        for ($i = 0; $i < $this->msgarray['requestsize']; $i++) {
            ?>
                    var html = '';
                    html += "<div id='parent_<?php echo $i; ?>' class='add_request col-md-6' >";
                    html += "<div class='form-group'>";
                    html += "<label class='col-md-3 control-label'>Question </label>";
                    html += "<div class='col-md-9'><input type='text' maxlength='100' value='<?php echo $_POST['question'][$i] ?>' id='question_<?php echo $i; ?>' name='question[]' class='cls_service_request_name form-control' onblur='validatequestionname(this)' onkeyup='validatequestionname(this)'>";
            <?php if (isset($this->msgarray['ques_name'][$i])) { ?>
                        html += "<span id='errors-question_<?php echo $i; ?>' class='errors'><?php echo $this->msgarray['ques_name'][$i]; ?></span>";
            <?php } ?>
                    html += "</div>";
                    html += "</div>";
                    html += "<div class='form-group'>";
                    html += "<label class='col-md-3 control-label'>Description</label>";
                    html += "<div class='col-md-9'><textarea maxlength='400' cols='30' rows='4' class='form-control' id='description_<?php echo $i; ?>' name='description[]'><?php echo ($_POST['description'][$i] != '' ? $_POST['description'][$i] : ''); ?></textarea></div>";
                    html += "</div>";
            <?php if ($i == 0) { ?>
                        html += "</div>";
                        html += "<span id='add-candidate'><span class='sprite candidate-new' onclick='addAppQuestionDiv()'>Add New Question</span></div>";
            <?php } else { ?>
                        html += "<div class='division'><span class='sprite remove-new remove-entry' title='Remove' onclick='removeDiv(<?php echo $i; ?>)'></span></div>";
                        html += "</div>";
            <?php } ?>
                    $('#multi_dept_div').append(html);
                    counter++;
                    $("[id^=description]").maxlength();

        <?php } ?>
                $('#idcount').val(counter);
    <?php }
} ?>

    });

</script>