<div class="form_cntr_block">
<?php 

if($this->ermsg != '')
{
?>
<div class="ml-alert-1-info m1-info-set-2">
    <div class="style-1-icon info"></div>
       No data found.
</div>
<?php 
}
else 
{
$data = $this->data;
$id = $this->id;
$previ_data = $this->previ_data;
$pa_category_name = $this->category_name;
//echo "cat_ID:".$pa_category_id;
//echo "<pre>"; print_r($data); echo "</pre>";
?>
<?php 
if($this->ermsg == '')  { ?>

<div class="total-form-controller cancel-set data-view-details">
    <div class="position_rel">
       
   </div>
   
    <div class="cofig_title" style="margin-left: 0px;padding-top: 0px;">Questions
	<?php
    if($previ_data == 'Yes')
    {
    ?>
    <div class="new-form-ui-submit "  style="margin-top: 0px; float: right; width: auto; margin-left: 0px; ">
       
			<div class="back-to-page" style="position: relative; float: right; top: 0px;">
				<input type="button" onclick="window.location.href='<?php echo BASE_URL; ?>appraisalquestions';" name="Back" value="Back">
			</div>
			<?php if($data['isused'] == 0) { ?>
            	<input type="button" class="fltright" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
            <?php } ?>		
        
    </div>
    <?php 
    }
    ?>
	</div>
   <?php 
sapp_Helper::viewHeader();
sapp_Helper::viewBody('alt','Parameter',(!empty( $pa_category_name))? $pa_category_name:"...",'Question',(!empty($this->data['question']))?$this->data['question']:"...");
sapp_Helper::viewBody('nor','Description',(!empty($this->data['description']))?$this->data['description']:"...",'','');
sapp_Helper::viewFooter();
?>
 
   </div>


<?php } }?>
</div>