 

<?php if($this->errorstring !=''){?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
						Unauthorized access
	</div>

<?php 
}
else
{

if (count($this->messages)) {?>
	<div id="dispmsgempleaves" class="settingssuccess">
		<?php foreach ($this->messages as $message){?>
		 <?php echo $this->escape($message); ?>
		<?php } ?>
	</div>	
	
<?php } ?>

<span id="error_message"></span>
<?php
if($this->call != 'ajaxcall'){
?>
<div class="form_cntr_single">

<div class="new-form-ui inputheight" id="respformitems">
<label>Status</label>
<div class="division">
  	<select id="statusid" name="statusid" class="select2-offscreen" tabindex="-1" onchange = "displayStatusdata('<?php echo $this->controllername; ?>')">
    <option label="Approved" value="<?php echo sapp_Global::_encrypt(2);?>">Approved</option>
    <option label="Cancelled" value="<?php echo sapp_Global::_encrypt(4);?>">Cancelled</option>	
	 <option label="Pending for approval" value="<?php echo sapp_Global::_encrypt(1);?>">Pending for approval</option>
	<option label="Rejected" value="<?php echo sapp_Global::_encrypt(3);?>">Rejected</option>
    
    </select>
</div>
</div>

</div>


<?php 
}

if($this->call == 'ajaxcall'){
	$div = ''; $endDiv = ''; 
} else { 
	$div = '<div id="grid_'.$this->dataArray[0]['objectname'].'" class="all-grid-control">'; $endDiv = '</div>';
}
	echo $div.'<div id="msg" style="display:none;font-style: oblique; font-weight: bold; color: green;""></div>'.$this->grid($this->dataArray[0]).$endDiv;

?>
<script type='text/javascript'>
$(document).ready(function(){
<?php if (count($this->messages)) {?>
      setTimeout(function(){
			$('#dispmsgempleaves').fadeOut('slow');
		},3000);
<?php } ?>



});

<?php if($this->statusidstring !=''){ ?>
       $('#statusid').val('<?php echo $this->statusidstring; ?>');
<?php }?>
</script>
<?php }?>
