<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php 	
if($this->ermsg !='')
{
?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				No data found.
	</div>
<?php 
}
else
{	 sapp_Global::generateClientValidations($this->form);?>
<?php if (count($this->messages)) {?>
	<div id="dispempwork" class="settingssuccess">
		<?php 
			foreach ($this->messages as $message)
			{
				$flag = array();				
				$flag = array_keys($message);
				echo "<div id='messageData' class='ml-alert-1-$flag[0]'><div style='display:block;'><span class='style-1-icon $flag[0]'></span>";
				echo $message[$flag[0]];
				echo "</div></div>";
			} 
		?>
	</div>
	
<?php } ?>
<div id="error_message" style="display:none;"></div>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="panel-title">Work Eligibility Document</div>
    </div>
<form class="form-horizontal" name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction();?>" method="<?php echo $this->form->getMethod(); ?>">
		<?php echo $this->form->id; ?>
       <div class="panel-body"> 
                    <div class="row">                                       
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="col-md-3 control-label required">Document Type <img class="tooltip" title="Ex: U.S.Passport, Permanent Resident Card" src="<?php echo MEDIA_PATH;?>images/help.png"></label>
			<div class="col-md-9"><?php echo $this->form->documenttype; ?></div>
			<?php if(isset($this->msgarray['documenttype'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->documenttype->getId(); ?>"><?php echo $this->msgarray['documenttype'];?></span>
			<?php }?>
			</div>
			
			 <div class="form-group">
                        <label class="col-md-3 control-label required">Issuing Authority</label>
			<div class="col-md-9"><?php echo $this->form->issuingauthority; ?></div>
			<?php if(isset($this->msgarray['issuingauthority'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->issuingauthority->getId(); ?>"><?php echo $this->msgarray['issuingauthority'];?></span>
			<?php }?>
			</div>
					
			 <div class="form-group">
                        <label class="col-md-3 control-label">Description</label>
			<div class="col-md-9"><?php echo $this->form->description; ?></div>
			</div>
		</div></div></div>
		<div class="panel-footer">
		<?php echo $this->form->submit; ?>
                    <button onclick="window.location.href='<?php echo BASE_URL; ?>workeligibilitydoctypes';" type="button" class="btn btn-danger" id="Cancel" name="Cancel">Cancel</button>
		</div>
</form>
</div>
<?php	}	?>
<script type='text/javascript'>
$(document).ready(function(){

<?php if (count($this->messages)) {?>
      setTimeout(function(){
			$('#dispempwork').fadeOut('slow');
		},3000);

<?php } ?>
});

</script>