 <div class="form_cntr_block">

<?php 
if($this->nodata != '')
{
?>
<div class="ml-alert-1-info m1-info-set-2">
    <div class="style-1-icon info"></div>
       No data found.
</div>
<?php 
}
else 
{

if($this->emailContactsData == '' || empty($this->emailContactsData)) { ?>
			No Data Found
<?php }else { ?>
<?php 
$group_email = $this->form->groupEmail->getValue();
sapp_Helper::viewHeader();
sapp_Helper::viewBody('alt','Business Unit',(!empty($this->data['unitname']))?$this->data['unitname']:"...",'Group',(!empty($this->data['group_name']))?$this->data['group_name']:"...");
sapp_Helper::viewBody('nor','Group Email ',(!empty($group_email))?$this->form->groupEmail->getValue():"...",'','');
sapp_Helper::viewFooter();
?>
   

	
		<div class="new-form-ui-submit">
        <input type="submit" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
        
        <button onclick="window.location.href='<?php echo BASE_URL; ?><?php echo $this->controllername;?>';" type="button" id="Cancel" name="Cancel">Cancel</button>
        </div>


<?php }} ?>
</div>