<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php sapp_Global::generateClientValidations($this->form);?>
<div id="error_message" style="display:none;"></div>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="panel-title">Manage External Users</div>
    </div>
<form class="form-horizontal"  name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction();?>" method="<?php echo $this->form->getMethod(); ?>">

		<?php echo $this->form->id; ?>
        <div class="panel-body">
            
                <div class="col-md-6">
                    <div class="form-group">
                <label class="col-md-3 control-label required">Group Name</label>
			<div class="col-md-9"><?php echo $this->form->groupname; ?></div>
			<?php if(isset($this->msgarray['groupname'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->groupname->getId(); ?>"><?php echo $this->msgarray['groupname'];?></span>
			<?php }?>
			</div>
								
			
                           <div class="form-group">
			  <label class="col-md-3 control-label">Description</label>
			<div class="col-md-9"><?php echo $this->form->description; ?></div>
			</div></div>
	</div>
		<div class="panel-footer">
		<?php echo $this->form->submit; ?>
                    <button onclick="window.location.href='<?php echo BASE_URL; ?>holidaygroups';" type="button" id="Cancel" class="btn btn-danger" name="Cancel">Cancel</button>
		</div>
</form></div>
