 <div class="form_cntr_block">
<?php 	
if($this->ermsg !='')
{
?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				No data found.
	</div>
<?php 
}
else
{
$baseUrl = $this->serverUrl().$this->baseUrl();
echo $this->form->id; ?>
<?php 
sapp_Helper::viewHeader();
sapp_Helper::viewBody('nor','Education Level',$this->data['educationlevelcode'],'Description',(!empty($this->data['description']))?$this->data['description']:"...");
sapp_Helper::viewFooter();
?>
 
		<div class="new-form-ui-submit">
			<input type="submit" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
			<button onclick="window.location.href='<?php echo BASE_URL; ?>educationlevelcode';" type="button" >Cancel</button>
		</div>
       
<?php	}	?>
</div>