 

<?php if (count($this->messages)) 
{?>
	<div id="dispscreeningtype" class="settingssuccess">
		<?php 
			foreach ($this->messages as $message)
			{
				$flag = array();				
				$flag = array_keys($message);
				echo "<div id='messageData' class='ml-alert-1-$flag[0]'><div style='display:block;'><span class='style-1-icon $flag[0]'></span>";
				echo $message[$flag[0]];
				echo "</div></div>";
			} 
		?>
	</div>	
	
<?php } 
if($this->call != 'ajaxcall'){
?>
<div id="error_message"></div>
<div class="form_cntr_single">
<div class="total-form-controller">
    <div class="new-form-ui" style="height:auto;">         
        <div class="division"><select id="statusid" name="statusid" class="select2-offscreen" tabindex="-1" onchange = "displayStatusdata('approvedrequisitions')">           
            <option value="<?php echo sapp_Global::_encrypt(2);?>">Approved</option>
            <option value="<?php echo sapp_Global::_encrypt(4);?>">Closed</option>
            <option value="<?php echo sapp_Global::_encrypt(6);?>">Complete</option>
			<option value="<?php echo sapp_Global::_encrypt(7);?>">In process</option>
			<option value="<?php echo sapp_Global::_encrypt(5);?>">On hold</option>
           </select>
        </div>
    </div>
</div>
</div>
<?php 
}
if($this->call == 'ajaxcall'){
	$div = ''; $endDiv = ''; 
} else { 
	$div = '<div id="grid_'.$this->dataArray['objectname'].'" class="all-grid-control mrgetop10">'; $endDiv = '</div>';
}
	echo $div.'<div id="msg" style="display:none;font-style: oblique; font-weight: bold; color: green;""></div>'.$this->requisitiongrid($this->dataArray).$endDiv;
?>
<script type="text/javascript" language="javascript">
$(document).ready(function(){
   
        <?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger');?>
    <?php if ($flashMessenger->setNamespace('success')->hasMessages()): ?>
            <?php foreach ($flashMessenger->getMessages() as $msg): ?>
                    successmessage('<?php echo trim($msg); ?>');                    
            <?php endforeach; ?>
    <?php endif; ?>
});

<?php if($this->statusidstring !=''){ ?>
       $('#statusid').val('<?php echo $this->statusidstring; ?>');
<?php }?>
</script>