<!DOCTYPE HTML>

 

<?php

$status =  sapp_Global::_checkstatus();
if($status == 'false')
{
    sapp_Global::_logout();
}
$request = Zend_Controller_Front::getInstance();
$module = $request->getRequest()->getModuleName();
$controllerName = $request->getRequest()->getControllerName();
$actionName = $request->getRequest()->getActionName();
$baseUrl = rtrim(BASE_URL, '/');

$auth = Zend_Auth::getInstance();

$loginUserName = ""; 
$loginUserId = '';
$tourflag = 0;
$loginProfileImgSrc = MEDIA_PATH.'images/profile__pic.jpg';
$loginuserRole = '';
$userfullname = '';
$loginuserGroup = '';

if($auth->hasIdentity())
{
    $loginUserId = $auth->getStorage()->read()->id;

   	/**
   	 * Handle error event on loading 'Profile image'.
   	 * file_exists() was used to avoid Network error in browser console
   	 */
	 $userProfileImage = $auth->getStorage()->read()->profileimg;
    if (!empty($userProfileImage) && file_exists("public/uploads/profile/".$userProfileImage)) {
    	$loginProfileImgSrc = DOMAIN."public/uploads/profile/".$userProfileImage;
    }
    $loginUserName =$auth->getStorage()->read()->employeeId;	    
    $loginuserRole = $auth->getStorage()->read()->emprole;	
    $loginuserGroup = $auth->getStorage()->read()->group_id;
    $tourflag = $auth->getStorage()->read()->tourflag;
    $userfullname = $auth->getStorage()->read()->userfullname;

}
 
$bgchecklinkpermission = '';
if($controllerName == 'employee')
    $bgchecklinkpermission = sapp_Global::_checkprivileges(BGCHECKS,$loginuserGroup,$loginuserRole,'add');
$storage = new Zend_Auth_Storage_Session();
$data = $storage->read();

$menu_data = '';

if($actionName == 'viewsettings'){
	
    $menu_data = $this->menubuilder("settings",$loginuserRole,1,$loginuserGroup);
}else{
	
    $menu_data = $this->menubuilder("",$loginuserRole,1,$loginuserGroup);
	
}

?>
<html><head>
<!-- META SECTION -->
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="expires" content="0">
<meta name="msapplication-tap-highlight" content="no" /> 
<title><?php echo APPLICATION_NAME; ?> - Human Resources Management System
</title>
<meta name="viewport" content="width=device-width, initial-scale=1">

<meta http-equiv="Content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="en-us" />
<!-- END META SECTION -->
<!-- CSS INCLUDE -->
<link rel="stylesheet" type="text/css" id="theme" href="<?php echo MEDIA_PATH_NEW;?>css/theme-default.css" />
<!-- EOF CSS INCLUDE -->	
<script  language="JavaScript" type="text/javascript" src="<?php echo MEDIA_PATH_NEW;?>js/plugins/jquery/jquery.min.js"></script>
    <script language="JavaScript" type="text/javascript" src="<?php echo MEDIA_PATH_NEW;?>js/plugins/jquery/jquery-ui.min.js"></script>
    <script language="JavaScript" type="text/javascript" src="<?php echo MEDIA_PATH_NEW;?>js/plugins/bootstrap/bootstrap.min.js"></script>
    <script language="JavaScript" type="text/javascript" src="<?php echo MEDIA_PATH; ?>jquery/js/slimScrollHorizontal.js"></script>
    <script language="JavaScript" type="text/javascript" src="<?php echo MEDIA_PATH;?>jquery/js/jquery.slimscroll.min.js"></script>
	

</head>
<body>

 <!-- START PAGE CONTAINER -->
    <div class="page-container">
       <div class="page-sidebar">
	   <ul class="x-navigation">
	   <li class="xn-logo"><a href="<?php echo $baseUrl; ?>/welcome">ATLANT</a> <a href="#" class="x-navigation-control">
                </a></li>
                <li class="xn-profile"><a href="#" class="profile-mini">
                    <img src="<?php echo $loginProfileImgSrc;?>" alt="<?php if(strlen($userfullname)>14){ echo substr($userfullname, 0, 14).'..'; } else {echo $userfullname;}?>" />
                </a>
				 <div class="profile">
                        <div class="profile-image">
                            <img src="<?php echo $loginProfileImgSrc;?>" alt="<?php if(strlen($userfullname)>14){ echo substr($userfullname, 0, 14).'..'; } else {echo $userfullname;}?>" />
                        </div>
                        <div class="profile-data">
                            <div class="profile-data-name">
                                <?php if(strlen($userfullname)>14){ echo substr($userfullname, 0, 14).'..'; } else {echo $userfullname;}?></div>
                            <div class="profile-data-title">
                                Web Developer/Designer</div>
                        </div>
                        <div class="profile-controls">
                            <a href="pages-profile.html" class="profile-control-left"><span class="fa fa-info"></span>
                            </a><a href="pages-messages.html" class="profile-control-right"><span class="fa fa-envelope">
                            </span></a>
                        </div>
                    </div>
                </li>
				
				<?php 
    if($loginuserRole == 1 || in_array($data->group_id,array(SYSTEMADMIN_GROUP,MANAGEMENT_GROUP,HR_GROUP,MANAGER_GROUP,EMPLOYEE_GROUP,USERS_GROUP,CUSTOM_GROUP)))
    {
        echo $menu_data['parent_menu'];
    }
    
?>
				</ul>
            <!-- END X-NAVIGATION -->
        </div>
        <!-- END PAGE SIDEBAR -->
        <!-- PAGE CONTENT -->
		<div class="page-content">
            <!-- START X-NAVIGATION VERTICAL -->
            <ul class="x-navigation x-navigation-horizontal x-navigation-panel">
                <!-- TOGGLE NAVIGATION -->
                <li class="xn-icon-button"><a href="#" class="x-navigation-minimize"><span class="fa fa-dedent">
                </span></a></li>
                <!-- END TOGGLE NAVIGATION -->
                <!-- SEARCH -->
                <li class="xn-search">
                    <form role="form">
                    <input type="text" name="search" placeholder="Search..." />
                    </form>
                </li>
                <!-- END SEARCH -->
                <!-- POWER OFF -->
                <li class="xn-icon-button pull-right last"><a href="#"><span class="fa fa-power-off">
                </span></a>
                    <ul class="xn-drop-left animated zoomIn">
                        <li><a href="<?php echo $baseUrl; ?>/dashboard/viewprofile"><span class="fa  fa-user"></span>View Profile</a></li>
						<li><a href="<?php echo $baseUrl; ?>/viewsettings/1"><span class="fa fa-wrench"></span>Settings</a></li>
						<li><a href="<?php echo $baseUrl; ?>/dashboard/changepassword"><span class="fa fa-lock"></span>Change Password</a></li>
						<?php 
if($loginuserRole == SUPERADMINROLE)
{
?>
        <li><a href="<?php echo $baseUrl; ?>/dashboard/emailsettings"><span class="fa fa-envelope-o"></span>Mail Settings</a></li>
<?php 
}
if($controllerName != "reports")
{
?>
    <li> <a href="#" id="tourLink"><span class="fa fa-caret-square-o-right"></span>Take Tour</a></li>
<?php
}
if($loginuserRole == SUPERADMINROLE)
{
?>
	<li><a href="<?php echo $baseUrl; ?>/dashboard/upgradeapplication"><span class="fa fa-cloud-upload"></span>Upgrade Application</a></li>
<?php }?>	
   
                        <li><a href="#" class="mb-control" data-box="#mb-signout"><span class="fa fa-sign-out">
                        </span>Sign Out</a></li>
                    </ul>
                </li>
                <!-- END POWER OFF -->
                <!-- MESSAGES -->
                <li class="xn-icon-button pull-right"><a href="#"><span class="fa fa-comments"></span>
                </a>
                    <div class="informer informer-danger">
                        4</div>
                    <div class="panel panel-primary animated zoomIn xn-drop-left xn-panel-dragging">
                        <div class="panel-heading">
                            <h3 class="panel-title">
                                <span class="fa fa-comments"></span>Messages</h3>
                            <div class="pull-right">
                                <span class="label label-danger">4 new</span>
                            </div>
                        </div>
                        <div class="panel-body list-group list-group-contacts scroll" style="height: 200px;">
                            <a href="#" class="list-group-item">
                                <div class="list-group-status status-online">
                                </div>
                                <img src="assets/images/users/user2.jpg" class="pull-left" alt="John Doe" />
                                <span class="contacts-title">John Doe</span>
                                <p>
                                    Praesent placerat tellus id augue condimentum</p>
                            </a><a href="#" class="list-group-item">
                                <div class="list-group-status status-away">
                                </div>
                                <img src="assets/images/users/user.jpg" class="pull-left" alt="Dmitry Ivaniuk" />
                                <span class="contacts-title">Dmitry Ivaniuk</span>
                                <p>
                                    Donec risus sapien, sagittis et magna quis</p>
                            </a><a href="#" class="list-group-item">
                                <div class="list-group-status status-away">
                                </div>
                                <img src="assets/images/users/user3.jpg" class="pull-left" alt="Nadia Ali" />
                                <span class="contacts-title">Nadia Ali</span>
                                <p>
                                    Mauris vel eros ut nunc rhoncus cursus sed</p>
                            </a><a href="#" class="list-group-item">
                                <div class="list-group-status status-offline">
                                </div>
                                <img src="assets/images/users/user6.jpg" class="pull-left" alt="Darth Vader" />
                                <span class="contacts-title">Darth Vader</span>
                                <p>
                                    I want my money back!</p>
                            </a>
                        </div>
                        <div class="panel-footer text-center">
                            <a href="pages-messages.html">Show all messages</a>
                        </div>
                    </div>
                </li>
                <!-- END MESSAGES -->
                <!-- TASKS -->
                <li class="xn-icon-button pull-right"><a href="#"><span class="fa fa-tasks"></span></a>
                    <div class="informer informer-warning">
                        3</div>
                    <div class="panel panel-primary animated zoomIn xn-drop-left xn-panel-dragging">
                        <div class="panel-heading">
                            <h3 class="panel-title">
                                <span class="fa fa-tasks"></span>Tasks</h3>
                            <div class="pull-right">
                                <span class="label label-warning">3 active</span>
                            </div>
                        </div>
                        <div class="panel-body list-group scroll" style="height: 200px;">
                            <a class="list-group-item" href="#"><strong>Phasellus augue arcu, elementum</strong>
                                <div class="progress progress-small progress-striped active">
                                    <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="50"
                                        aria-valuemin="0" aria-valuemax="100" style="width: 50%;">
                                        50%</div>
                                </div>
                                <small class="text-muted">John Doe, 25 Sep 2015 / 50%</small> </a><a class="list-group-item"
                                    href="#"><strong>Aenean ac cursus</strong>
                                    <div class="progress progress-small progress-striped active">
                                        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="80"
                                            aria-valuemin="0" aria-valuemax="100" style="width: 80%;">
                                            80%</div>
                                    </div>
                                    <small class="text-muted">Dmitry Ivaniuk, 24 Sep 2015 / 80%</small> </a>
                            <a class="list-group-item" href="#"><strong>Lorem ipsum dolor</strong>
                                <div class="progress progress-small progress-striped active">
                                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="95"
                                        aria-valuemin="0" aria-valuemax="100" style="width: 95%;">
                                        95%</div>
                                </div>
                                <small class="text-muted">John Doe, 23 Sep 2015 / 95%</small> </a><a class="list-group-item"
                                    href="#"><strong>Cras suscipit ac quam at tincidunt.</strong>
                                    <div class="progress progress-small">
                                        <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0"
                                            aria-valuemax="100" style="width: 100%;">
                                            100%</div>
                                    </div>
                                    <small class="text-muted">John Doe, 21 Sep 2015 /</small><small class="text-success">
                                        Done</small> </a>
                        </div>
                        <div class="panel-footer text-center">
                            <a href="pages-tasks.html">Show all tasks</a>
                        </div>
                    </div>
                </li>
                <!-- END TASKS -->
                <!-- LANG BAR -->
                <li class="xn-icon-button pull-right"><a href="#"><span class="flag flag-gb"></span>
                </a>
                    <ul class="xn-drop-left xn-drop-white animated zoomIn">
                        <li><a href="#"><span class="flag flag-gb"></span>English</a></li>
                        <li><a href="#"><span class="flag flag-de"></span>Deutsch</a></li>
                        <li><a href="#"><span class="flag flag-cn"></span>Chinese</a></li>
                    </ul>
                </li>
                <!-- END LANG BAR -->
            </ul>
            <!-- END X-NAVIGATION VERTICAL -->
            <!-- START BREADCRUMB -->
            <ul class="breadcrumb">
                <li><a href="#">Home</a></li>
                <li class="active">Dashboard</li>
            </ul>
            <!-- END BREADCRUMB -->
            <!-- PAGE CONTENT WRAPPER -->
            <div class="page-content-wrap">
			<div class="row">

