<div class="form_cntr_block">
<?php 

if($this->ermsg != '')
{
?>
<div class="ml-alert-1-info m1-info-set-2">
    <div class="style-1-icon info"></div>
       No data found.
</div>
<?php 
}
else 
{
$data = $this->data;
$id = $this->id;
$previ_data = $this->previ_data;

?>
<?php 
if($this->ermsg == '')  { ?>

<div class="total-form-controller cancel-set data-view-details">
    <div class="position_rel">
       
   </div>
   <?php
    /*if($previ_data == 'Yes')
    {
    ?>
    <div class="edit-btn">
        <div class="new-form-ui-submit ">
            <input type="button" class="fltright" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />        
        </div>
    </div>
    <?php 
    }*/
    ?>
     
    <div class="cofig_title" style="margin-left: 0px;padding-top: 0px;">Skills
		<div class="new-form-ui-submit "  style="margin-top: 0px; float: right; width: auto; margin-left: 0px; ">
			
				<div class="back-to-page" style="position: relative; float: right; top: 0px;">
					<input type="button" onclick="window.location.href='<?php echo BASE_URL; ?>appraisalskills';" name="Back" value="Back">
				</div>
			
		</div>
	</div>
	<?php 
sapp_Helper::viewHeader();
sapp_Helper::viewBody('alt','Skill ',(!empty($this->data['skill_name']))?$this->data['skill_name']:"...",'Description',(!empty($this->data['description']))?$this->data['description']:"...");
sapp_Helper::viewFooter();
?>
 </div>


<?php } }?></div>