<div class="form_cntr_block"><?php 
 
		if($this->ermsg !='')
		{
?>
     <div class="ml-alert-1-info m1-info-set"><div class="style-1-icon info"></div>No data found.</div>
<?php 
}
else
{
$baseUrl = $this->serverUrl().$this->baseUrl();
echo $this->form->id; ?>
<?php 
sapp_Helper::viewHeader();
sapp_Helper::viewBody('nor','Country',$this->data['countryid'],'State',$this->data['state']);
sapp_Helper::viewBody('alt','City',$this->data['city'],'','');
sapp_Helper::viewFooter();
?>

		<div class="new-form-ui-submit">									
            <input onclick="window.location.href='<?php echo BASE_URL; ?>cities';" type="button"  value="Back"  />
		</div>
		
<script type='text/javascript'>
 <?php if($this->cityValue!='') { ?>	
			var Cityval = '<?php echo $this->cityValue; ?>';								
			var cityData = document.getElementById('city');
												
			for(var i = 0 ; i <= cityData.length ; i++)
			{
				if(cityData.options[i] !== undefined)
				{										
					if (cityData.options[i].value == Cityval) 
					{						
                                            cityData.options[i].selected = true;											
                                            break;
					}
				}
			}
			
	<?php } ?>	
</script>
<?php } ?></div>