 

<?php 
if($this->ermsg !='')
{
?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				No data found.
	</div>
<?php 
}
else
{
sapp_Global::generateClientValidations($this->form);
if($this->emptyFlag != 0)
	{
?>
<?php	}	?>
<div id="error_message" style="display:none;"></div>

<form name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction();?>" method="<?php echo $this->form->getMethod(); ?>">
	<div class="form_cntr_block"> <?php echo $this->form->id; 
			echo $this->form->emptyFlag; 
		?>
        <div class="total-form-controller">
		    <div class="new-form-ui">
			  <label class="required">Payment Mode</label>
			<div class="division"><?php echo $this->form->payment_method_name; ?>
			<?php if(isset($this->msgarray['payment_method_name'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->payment_method_name->getId(); ?>"><?php echo $this->msgarray['payment_method_name'];?></span>
			<?php }?>
			</div>
			</div>
			
			
		<div class="new-form-ui-submit">
		<?php echo $this->form->submit; ?>
		<button onclick="window.location.href='<?php echo BASE_URL; ?>expenses/paymentmode';" type="button" id="Cancel" name="Cancel">Cancel</button>
		</div></div>
		</div> 
</form>


<?php	}	?>
