<?php 
 
 if (count($this->messages)) {?>
	<div id="dispmsgtrips">
    <?php 
			foreach ($this->messages as $message)
			{
				$flag = array();				
				$flag = array_keys($message);
				echo "<div id='messageData' class='ml-alert-1-$flag[0]' style='margin-bottom: 0px;'><div style='display:block;'><span class='style-1-icon $flag[0]'></span>";
				echo $message[$flag[0]];
				echo "</div></div>";
			} 
	?>	
   </div>  
<?php } ?>
<span id="error_message"></span>
<?php 
if($this->call == 'ajaxcall'){
	$div = ''; $endDiv = ''; 
} else { 
	$div = '<div id="grid_'.$this->dataArray[0]['objectname'].'" class="all-grid-control">'; $endDiv = '</div>';
}
	//echo "<pre>";print_r($this->dataArray[0]);exit;
	//echo "here";exit;
	echo $div.'<div id="msg" style="display:none;font-style: oblique; font-weight: bold; color: green;""></div>'.$this->gridtm($this->dataArray[0]).$endDiv;
	
?>
<script type='text/javascript'>
$(document).ready(function(){

<?php if (count($this->messages)) {?>
      setTimeout(function(){
			$('#dispmsgtrips').fadeOut('slow');
		},3000);
<?php } ?>
});
</script>