 

<?php 
if($this->ermsg !='')
{
?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
						No data found.
	</div>

<?php
}else
{

 sapp_Global::generateClientValidations($this->form);
?>
<div id="error_message" style="display:none;"></div>

<form name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction();?>" method="<?php echo $this->form->getMethod(); ?>">
		<div class="form_cntr_block"><?php echo $this->form->id; ?>
        <div class="total-form-controller">
		    <div class="new-form-ui clearb">
			  <label class="required">Marital Code <img class="tooltip" title="Ex: M, S, D" src="<?php echo $this->baseUrl().'/public/media/';?>images/help.png"></label>
			<div class="division"><?php echo $this->form->maritalcode; ?></div>
			<?php if(isset($this->msgarray['maritalcode'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->maritalcode->getId(); ?>"><?php echo $this->msgarray['maritalcode'];?></span>
			<?php }?>
			</div>
			
			<div class="new-form-ui clearb">
			  <label class="required">Marital Status <img class="tooltip" title="Ex: Married, Single, Divorced" src="<?php echo $this->baseUrl().'/public/media/';?>images/help.png"> </label>
			<div class="division"><?php echo $this->form->maritalstatusname; ?></div>
			<?php if(isset($this->msgarray['maritalstatusname'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->maritalstatusname->getId(); ?>"><?php echo $this->msgarray['maritalstatusname'];?></span>
			<?php }?>
			</div>
					
			<div class="new-form-ui clearb textareaheight">
			  <label>Description</label>
			<div class="division"><?php echo $this->form->description; ?></div>
			</div>
		<div class="new-form-ui-submit">
		<?php echo $this->form->submit; ?>
		<button onclick="window.location.href='<?php echo BASE_URL; ?>maritalstatus';" type="button" id="Cancel" name="Cancel">Cancel</button>
		</div>
</div></div>
</form>
<?php }?> 