<?php 
 
if($this->ermsg !='')
{
?>
     <div class="ml-alert-1-info m1-info-set"><div class="style-1-icon info"></div>No data found.</div>
<?php 
}
else
{	 sapp_Global::generateClientValidations($this->form);?>
<div id="error_message" style="display:none;"></div>

<form name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction();?>" method="<?php echo $this->form->getMethod(); ?>">
		<div class="form_cntr_block"><?php echo $this->form->id; ?>
        <div class="total-form-controller">
		    <div class="new-form-ui clearb">
			  <label class="required">Competency Level <img class="tooltip" title="Ex: Basic, Intermediately" src="<?php echo MEDIA_PATH;?>images/help.png"></label>
			<div class="division"><?php echo $this->form->competencylevel; ?></div>
			<?php if(isset($this->msgarray['competencylevel'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->competencylevel->getId(); ?>"><?php echo $this->msgarray['competencylevel'];?></span>
			<?php }?>
			</div>
					
			<div class="new-form-ui clearb textareaheight">
			  <label>Description</label>
			<div class="division"><?php echo $this->form->description; ?></div>
			</div>
        </div>
		
		<div class="new-form-ui-submit">
		<?php echo $this->form->submit; ?>
		<button onclick="window.location.href='<?php echo BASE_URL; ?>competencylevel';" type="button" id="Cancel" name="Cancel">Cancel</button>
		</div></div>
</form>
<?php	}	?>