<?php
/* * ******************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 * ****************************************************************************** */
?>

<?php
sapp_Global::generateClientValidations($this->form);
if ($this->emptyFlag != 0) {
    ?>	 <div class="ml-alert-1-info m1-info-set">
        <div class="style-1-icon info"></div>
        Job titles are not configured yet.
    </div>
<?php } ?>
<div id="error_message" style="display:none;"></div>
<div class="page-content-wrap">
    <div class="panel-heading">
        <h3 class="panel-title"><strong>Position</strong> Add</h3>
        <ul class="panel-controls">
            <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
        </ul>
    </div>
   <div class="panel panel-default">
    <div class="panel-heading">
        <div class="panel-title">Positions</div>
    </div>
        <form class="form-horizontal" name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>">
            <?php
            echo $this->form->id;
            echo $this->form->emptyFlag;
            ?>
             <div class="panel-body"> 
            <div class="row">                                       
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="col-md-3 control-label">Job Title</label>
                        <div class="col-md-9"> <?php echo $this->form->jobtitleid; ?>
                            <?php if (isset($this->msgarray['jobtitleid'])) { ?>
                                <span class="errors" id="errors-<?php echo $this->form->jobtitleid->getId(); ?>"><?php echo $this->msgarray['jobtitleid']; ?></span>
                            <?php } ?>

                            <?php if ($this->popConfigPermission == 'Yes') { ?>	
                                <span class="add-coloum" onclick="displaydeptform('<?php echo BASE_URL . 'jobtitles/addpopup' ?>', 'Job Titles');"> Add Job Title</span>			
<?php } ?>

                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label">Position</label>
                        <div class="col-md-9"><?php echo $this->form->positionname; ?></div>
                        <span class="help-block"> '</span>
                        <?php if (isset($this->msgarray['positionname'])) { ?>
                            <span class="errors" id="errors-<?php echo $this->form->positionname->getId(); ?>"><?php echo $this->msgarray['positionname']; ?></span>
<?php } ?>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label">Description</label>
                        <div class="col-md-9 col-xs-12"><?php echo $this->form->description; ?></div>
                    </div>
                </div>
            </div>

    </div> 
    <div class="panel-footer">

<?php echo $this->form->submit; ?>
        <button onclick="window.location.href = '<?php echo BASE_URL; ?>positions';" type="button" id="Cancel" class="btn btn-danger" name="Cancel">Cancel</button>
    </div>

</form>
   </div>
<div id="jobtitlesContainer"  style="display: none; overflow: auto;">
    <div class="heading">
        <a href="javascript:void(0)">
            <img src="<?php echo $this->baseUrl() . '/public/media/'; ?>images/close.png" name="" align="right" border="0" hspace="3" vspace="5" class="closeAttachPopup" style="margin: -24px 8px 0 0;"> </a>
    </div>

    <iframe id="jobtitlesCont" class="business_units_iframe" frameborder="0"></iframe>
</div>
