<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php 
if($this->ermsg !='')
{
?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				No data found.
	</div>
<?php 
}
else
{
 sapp_Global::generateClientValidations($this->form);?>
<div id="error_message" style="display:none;"></div>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="panel-title">Pay Frequency</div>
    </div>
<form class="form-horizontal"  name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction();?>" method="<?php echo $this->form->getMethod(); ?>">
	<?php echo $this->form->id; ?>
         <div class="panel-body">
            
                <div class="col-md-6">
                    <div class="form-group">
                <label class="col-md-3 control-label required"><?php echo $this->form->freqtype->getLabel();?>  <img class="tooltip" title="Ex: Hour, Day, Week" src="<?php echo MEDIA_PATH;?>images/help.png"></label>
			<div class="col-md-9"><?php echo $this->form->freqtype; ?></div>
			<?php if(isset($this->msgarray['freqtype'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->freqtype->getId(); ?>"><?php echo $this->msgarray['freqtype'];?></span>
			<?php }?>
			</div>
			
			 <div class="form-group">
                <label class="col-md-3 control-label required"><?php echo $this->form->freqcode->getLabel();?> <img class="tooltip" title="Ex: Hr, Dy, Wk" src="<?php echo MEDIA_PATH;?>images/help.png"></label>
			<div class="col-md-9"><?php echo $this->form->freqcode; ?></div>
			<?php if(isset($this->msgarray['freqcode'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->freqcode->getId(); ?>"><?php echo $this->msgarray['freqcode'];?></span>
			<?php }?>
			</div>
								
			 <div class="form-group">
                <label class="col-md-3 control-label">Description</label>
			<div class="col-md-9"><?php echo $this->form->freqdescription; ?></div>
			</div>
		</div>
		<div class="panel-footer">
		<?php echo $this->form->submit; ?>
                    <button onclick="window.location.href='<?php echo BASE_URL; ?>payfrequency';" type="button" id="Cancel" class="btn btn-danger" name="Cancel">Cancel</button>
		</div>
</div>
</form></div>
<?php	}	?>
