 

<?php 
if (count($this->messages)) 
{?>
	<div id="dispscreeningtype" class="settingssuccess">
		<?php 
			foreach ($this->messages as $message)
			{
				$flag = array();				
				$flag = array_keys($message);
				echo "<div id='messageData' class='ml-alert-1-$flag[0]'><div style='display:block;'><span class='style-1-icon $flag[0]'></span>";
				echo $message[$flag[0]];
				echo "</div></div>";
			} 
		?>
	</div>	
	
<?php } 
if($this->call != 'ajaxcall'){
?><div class="form_cntr_single">
<div class="total-form-controller">
    <div class="new-form-ui inputheight-2"> 
        <div class="division"><select id="statusid" name="statusid" class="select2-offscreen" tabindex="-1" onchange = "displayStatusdata('shortlistedcandidates')">
            <option value="<?php echo sapp_Global::_encrypt(0);?>">All Candidates</option>
			<option value="<?php echo sapp_Global::_encrypt(1);?>">Shortlisted Candidates</option>           
            <option value="<?php echo sapp_Global::_encrypt(2);?>">Selected Candidates</option>            
			<option value="<?php echo sapp_Global::_encrypt(3);?>">Rejected Candidates</option>            
            </select>
        </div>
    </div>
</div></div>
<?php 
}
?>
<div id="error_message"></div><?php 
if($this->call == 'ajaxcall'){
	$div = ''; $endDiv = ''; 
} else { 
	$div = '<div id="grid_'.$this->dataArray['objectname'].'" class="all-grid-control">'; $endDiv = '</div>';
}
	echo $div.'<div id="msg" style="display:none;font-style: oblique; font-weight: bold; color: green;""></div>'.$this->requisitiongrid($this->dataArray).$endDiv;
?>
<script type="text/javascript" language="javascript">

<?php if($this->statusidstring !=''){ ?>
       $('#statusid').val('<?php echo $this->statusidstring; ?>');
<?php }?>
</script>