 
<div class="form_cntr_block">
<?php 
if($this->ermsg !='')
{
?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				No data found.
	</div>
<?php
}
else
{ 
$baseUrl = $this->serverUrl().$this->baseUrl();
echo $this->form->id; ?>
<?php 
sapp_Helper::viewHeader();
sapp_Helper::viewBody('nor','Job Title Code',$this->data['jobtitlecode'],'Job Title',$this->data['jobtitlename']);
sapp_Helper::viewBody('alt','Job Description',(!empty($this->data['jobdescription']))?$this->data['jobdescription']:"...",'Min Experience Required',(!empty($this->data['minexperiencerequired']))?$this->data['minexperiencerequired']:"...");
sapp_Helper::viewBody('nor','Job Pay Grade Code',$this->data['jobpaygradecode'],'Job Pay Frequency',$this->data['jobpayfrequency']);
sapp_Helper::viewBody('alt','Comments',(!empty($this->data['comments']))?$this->data['comments']:"...",'','');
sapp_Helper::viewFooter();
?>
        <div class="new-form-ui-submit">
			<input type="submit" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
			<button onclick="window.location.href='<?php echo BASE_URL; ?>jobtitles';" type="button" >Cancel</button>
		</div>
    
<?php	}	?>   
</div>