<?php 
 
if($this->ermsg !='')
		{
?>
     <div class="ml-alert-1-info m1-info-set"><div class="style-1-icon info"></div>No data found.</div>
<?php }else
	{
		 if($this->popup == 'close') { ?> 	
			<div class="ml-alert-1-success">
			<div class="style-1-icon success"></div>
			Category <?php echo $this->eventact; ?> successfully
			</div>
		
		<?php 	 }else{ 	
		 sapp_Global::generateClientValidations($this->form);
		 $request = Zend_Controller_Front::getInstance();
		 $actionName = $request->getRequest()->getActionName();
		 	if($actionName == 'view')
		 	  $viewclass = 'view-form-detail';
		 	else
		 	  $viewclass = '';  
		 ?>
			<div id="error_message" style="display:none;"></div>
			<form name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction();?>" method="<?php echo $this->form->getMethod(); ?>">
			
			<div class="form_cntr_block">
					<input type="hidden" id="empid" value="<?php echo $this->id;?>">
					<?php $this->form->getAction();?>
			        <div class="total-form-controller <?php echo $viewclass;?>">
			               <?php  if($this->flag!='view'){?>
						<?php echo sapp_Helper::sd_form_helper($this->msgarray, $this->form, 'firstname', '','','required',array());?>
						<?php echo sapp_Helper::sd_form_helper($this->msgarray, $this->form, 'lastname', '','','',array());?>
						<?php echo sapp_Helper::sd_form_helper($this->msgarray, $this->form, 'contactnumber', '','','',array());?>
						<?php echo sapp_Helper::sd_form_helper($this->msgarray, $this->form, 'emailaddress', '','','',array());?>
						<?php //echo sapp_Helper::sd_form_helper($this->msgarray, $this->form, 'Componentid', '','','',array());?>
                                                
							<?php }else{
								sapp_Helper::viewHeader();
                                sapp_Helper::viewBody('alt','First Name',(!empty($this->data['firstname']))?$this->data['firstname']:"...",'Email',(!empty($this->data['emailaddress']))?$this->data['emailaddress']:"...");
                                sapp_Helper::viewFooter();
								}
							 ?>	
					<div class="new-form-ui-submit">
					<?php echo $this->form->submit; ?>
					<?php if($actionName == 'addpopup') { ?>
					    <button onclick="closeiframepopup('<?php echo $this->controllername;?>','cancel');"  type="button" >Cancel</button>
					<?php }else{?>
						<?php if($actionName == 'view'){?>
							<input type="button" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
						<?php }?>
						<button onclick="window.location.href='<?php echo BASE_URL; ?>downloadpayslip';" type="button" id="Cancel" name="Cancel">Cancel</button>
					<?php }?>	
					</div>
                                    <div id="gridView"></div>
				</div></div>
				
			</form>
<!--                       <div class="new-form-ui-submit" id="saveempcomp"><input type="button" value="Update" id="savecomponents"></div>-->
<?php }?>
<!--<script language='javascript' type='text/javascript'>

	<?php if($this->popup != '') { ?>
	  closeiframeAddPopup("<?php echo $this->departmentData ;?>",'<?php echo $this->controllername; ?>','service_desk_id','category'); 					
	<?php } ?>
</script>-->

<?php  }?>

 <script type='text/javascript'>
         $(document).ready(function(){
             $("#submitbutton").hide();
             $("#Cancel").hide();
             var url = document.location.pathname;
             var empid = url.substring(url.lastIndexOf('/') + 1);
        
	
             $.post(base_url+"/index/getdownloadayslip",{emp_id:empid},function(data){
              
                      var table = $("<table border='2' style='width:100%;'>");
                       table.append("<tr><th>EmployeeId</th>&nbsp;&nbsp;<th>Month</th><th>Year</th><th>Download</th></tr>");
                       var obj = JSON.parse(data);
                      
                       var html ='';
                       for(var i = 0; i < obj.length; i++) {
                            var item = obj[i];
                            var month=GetMonth(item.month);
                            
                            html += "<tr>";
                                                 
                            payslipUrl =  base_url + "/.."+ item.payrollurl;
                           
                            html += "<td ><label>"+item.empid+"</label></td><td style='text-align:center'><label>"+month+"</label></td><td style='text-align:center'><label>"+item.year+"</label></td><td style='text-align:center'><a href="+payslipUrl+" target='_blank' style='color:red;font-size:25px'><i class='fa fa-file-pdf-o' aria-hidden='true'></i></i></a></td></tr>";
     
                        }
                         table.append(html);
                         table.append("</table>");
                         if(obj !='')
                         {
                            $("#gridView").append(table);
                         }else
                         {
                              $("#gridView").append("<span id='nopayslip' style='font-size: 200%;color:red; float: left;'>Payslips are not found</span>");
                         }
                         
//              
	    });
          
         
     
    });
	
    function GetMonth(id){
    var text;
   var value=id;
    switch(value){
            case '1':
            text='Jan';
            break;
    case '2':
            text='Feb';
            break;
    case '3':
            text='Mar';
            break;
    case '4':
            text='Apr';
            break;
    case '5':
            text='May';
            break;
    case '6':
            text='Jun';
            break;
      case '7':
            text='Jul';
            break;
    case '8':
            text='Aug';
            break;
    case '9':
            text='Sep';
            break;
    case '10':
            text='Oct';
            break;
     case '11':
            text='Nov';
            break;
    case '12':
            text='Dec';
            break;
     default:
    text = "";

    }

    return text;
    }
       
     </script>
                        