<?php
/* * ******************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 * ****************************************************************************** */
if ($this->ermsg != '') {
    ?>
    <div class="ml-alert-1-info m1-info-set"><div class="style-1-icon info"></div>No data found.</div>
<?php
} else {
    if ($this->popup == 'close') {
        ?> 	
        <div class="ml-alert-1-success">
            <div class="style-1-icon success"></div>
            Category <?php echo $this->eventact; ?> successfully
        </div>

    <?php
    } else {
        sapp_Global::generateClientValidations($this->form);
        $request = Zend_Controller_Front::getInstance();
        $actionName = $request->getRequest()->getActionName();
        if ($actionName == 'view')
            $viewclass = 'view-form-detail';
        else
            $viewclass = '';
        ?>
        <div id="error_message" style="display:none;"></div>
        <form name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>"><div class="form_cntr_block">
            <input type="hidden" id="empid" value="<?php echo $this->id; ?>">
                <?php $this->form->getAction(); ?>
            <div class="total-form-controller <?php echo $viewclass; ?>">
                <?php if ($this->flag != 'view') { ?>
                    <?php echo sapp_Helper::sd_form_helper($this->msgarray, $this->form, 'shortname', '', '', 'required', array()); ?>
                    <?php echo sapp_Helper::sd_form_helper($this->msgarray, $this->form, 'FormulaType', '', '', '', array()); ?>
                    <?php echo sapp_Helper::sd_form_helper($this->msgarray, $this->form, 'Operator', '', '', '', array()); ?>
                    <?php echo sapp_Helper::sd_form_helper($this->msgarray, $this->form, 'IsOnDays', '', '', '', array()); ?>
                    <?php echo sapp_Helper::sd_form_helper($this->msgarray, $this->form, 'DomainFormula', '', '', '', array()); ?>

                <?php
                } else {
                    sapp_Helper::viewHeader();
                    sapp_Helper::viewBody('alt', 'shortname', (!empty($this->data['shortname'])) ? $this->data['shortname'] : "...", 'Formula', (!empty($this->data['DomainFormula'])) ? $this->data['DomainFormula'] : "...");
                    sapp_Helper::viewFooter();
                }
                ?>	
                <div class="new-form-ui-submit">
                    <?php echo $this->form->submit; ?>
                    <?php if ($actionName == 'addpopup') { ?>
                        <button onclick="closeiframepopup('<?php echo $this->controllername; ?>', 'cancel');"  type="button" >Cancel</button>
                    <?php } else { ?>
                        <?php if ($actionName == 'view') { ?>
                            <input type="button" onclick="changeeditscreen('<?php echo $this->controllername; ?>',<?php echo $this->id; ?>);" value="Edit" />
                        <?php } ?>
                        <button onclick="window.location.href = '<?php echo BASE_URL; ?>formulafields';" type="button" id="Cancel" name="Cancel">Cancel</button>
        <?php } ?>	
                </div>
                <div id="gridView"></div>
            </div>
</div>
        </form>
       
    <?php } ?>
    <!--<script language='javascript' type='text/javascript'>

    <?php if ($this->popup != '') { ?>
        closeiframeAddPopup("<?php echo $this->departmentData; ?>",'<?php echo $this->controllername; ?>','service_desk_id','category'); 					
    <?php } ?>
    </script>-->

<?php } ?>
